// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import type { Registry } from "./schema"

export const examples: Registry = [
  {
    name: "ActionRowDemo",
    type: "registry:example",
    registryDependencies: ["action-row"],
    files: [
      {
        path: "examples/ActionRowDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "AppLauncherDemo",
    type: "registry:example",
    registryDependencies: ["app-launcher"],
    files: [
      {
        path: "examples/AppLauncherDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "AttachmentDemo",
    type: "registry:example",
    registryDependencies: ["attachment"],
    files: [
      {
        path: "examples/AttachmentDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "AvatarDemo",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "examples/AvatarDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "BadgeDemo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [
      {
        path: "examples/BadgeDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "BotCommandCardDemo",
    type: "registry:example",
    registryDependencies: ["bot-command-card"],
    files: [
      {
        path: "examples/BotCommandCardDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ButtonDemo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "examples/ButtonDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "CardDemo",
    type: "registry:example",
    registryDependencies: ["card"],
    files: [
      {
        path: "examples/CardDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ChannelHeaderDemo",
    type: "registry:example",
    registryDependencies: ["channel-header"],
    files: [
      {
        path: "examples/ChannelHeaderDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ChannelInfoDemo",
    type: "registry:example",
    registryDependencies: ["channel-info"],
    files: [
      {
        path: "examples/ChannelInfoDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ChannelTopicDemo",
    type: "registry:example",
    registryDependencies: ["channel-topic"],
    files: [
      {
        path: "examples/ChannelTopicDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ChannelWelcomeDemo",
    type: "registry:example",
    registryDependencies: ["channel-welcome"],
    files: [
      {
        path: "examples/ChannelWelcomeDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ChatDemo",
    type: "registry:example",
    registryDependencies: ["chat"],
    files: [
      {
        path: "examples/ChatDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ChatWindowDemo",
    type: "registry:example",
    registryDependencies: ["chat-window"],
    files: [
      {
        path: "examples/ChatWindowDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "CodeBlockDemo",
    type: "registry:example",
    registryDependencies: ["code-block"],
    files: [
      {
        path: "examples/CodeBlockDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "CommandPanelDemo",
    type: "registry:example",
    registryDependencies: ["command-panel"],
    files: [
      {
        path: "examples/CommandPanelDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ContextMenuDemo",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    files: [
      {
        path: "examples/ContextMenuDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "CooldownBarDemo",
    type: "registry:example",
    registryDependencies: ["cooldown-bar"],
    files: [
      {
        path: "examples/CooldownBarDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "DirectionDemo",
    type: "registry:example",
    registryDependencies: ["direction"],
    files: [
      {
        path: "examples/DirectionDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "DividerDemo",
    type: "registry:example",
    registryDependencies: ["divider"],
    files: [
      {
        path: "examples/DividerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "DropdownDemo",
    type: "registry:example",
    registryDependencies: ["dropdown"],
    files: [
      {
        path: "examples/DropdownDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "EmbedDemo",
    type: "registry:example",
    registryDependencies: ["embed"],
    files: [
      {
        path: "examples/EmbedDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "EmptyStateDemo",
    type: "registry:example",
    registryDependencies: ["empty-state"],
    files: [
      {
        path: "examples/EmptyStateDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "FormFieldsDemo",
    type: "registry:example",
    registryDependencies: ["form-fields"],
    files: [
      {
        path: "examples/FormFieldsDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "InlineCodeDemo",
    type: "registry:example",
    registryDependencies: ["inline-code"],
    files: [
      {
        path: "examples/InlineCodeDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "InviteDemo",
    type: "registry:example",
    registryDependencies: ["invite"],
    files: [
      {
        path: "examples/InviteDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "KbdTagDemo",
    type: "registry:example",
    registryDependencies: ["kbd-tag"],
    files: [
      {
        path: "examples/KbdTagDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MemberListDemo",
    type: "registry:example",
    registryDependencies: ["member-list"],
    files: [
      {
        path: "examples/MemberListDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MentionDemo",
    type: "registry:example",
    registryDependencies: ["mention"],
    files: [
      {
        path: "examples/MentionDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MessageComposerDemo",
    type: "registry:example",
    registryDependencies: ["message-composer"],
    files: [
      {
        path: "examples/MessageComposerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MessageGroupDemo",
    type: "registry:example",
    registryDependencies: ["message-group"],
    files: [
      {
        path: "examples/MessageGroupDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MessageListDemo",
    type: "registry:example",
    registryDependencies: ["message-list"],
    files: [
      {
        path: "examples/MessageListDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ModalDemo",
    type: "registry:example",
    registryDependencies: ["modal"],
    files: [
      {
        path: "examples/ModalDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "NotifBadgeDemo",
    type: "registry:example",
    registryDependencies: ["notif-badge"],
    files: [
      {
        path: "examples/NotifBadgeDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "PaginationDemo",
    type: "registry:example",
    registryDependencies: ["pagination"],
    files: [
      {
        path: "examples/PaginationDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "PermissionDemo",
    type: "registry:example",
    registryDependencies: ["permission"],
    files: [
      {
        path: "examples/PermissionDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ProgressDemo",
    type: "registry:example",
    registryDependencies: ["progress"],
    files: [
      {
        path: "examples/ProgressDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "RadioDemo",
    type: "registry:example",
    registryDependencies: ["radio"],
    files: [
      {
        path: "examples/RadioDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ReactionDemo",
    type: "registry:example",
    registryDependencies: ["reaction"],
    files: [
      {
        path: "examples/ReactionDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ReplyPreviewDemo",
    type: "registry:example",
    registryDependencies: ["reply-preview"],
    files: [
      {
        path: "examples/ReplyPreviewDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "RoleTagDemo",
    type: "registry:example",
    registryDependencies: ["role-tag"],
    files: [
      {
        path: "examples/RoleTagDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ScrollbarDemo",
    type: "registry:example",
    registryDependencies: ["scrollbar"],
    files: [
      {
        path: "examples/ScrollbarDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SelectMenuDemo",
    type: "registry:example",
    registryDependencies: ["select-menu"],
    files: [
      {
        path: "examples/SelectMenuDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ServerBannerDemo",
    type: "registry:example",
    registryDependencies: ["server-banner"],
    files: [
      {
        path: "examples/ServerBannerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ServerSidebarDemo",
    type: "registry:example",
    registryDependencies: ["server-sidebar"],
    files: [
      {
        path: "examples/ServerSidebarDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SkeletonDemo",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "examples/SkeletonDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SlashCommandDemo",
    type: "registry:example",
    registryDependencies: ["slash-command"],
    files: [
      {
        path: "examples/SlashCommandDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SlashCommandSuggestionsDemo",
    type: "registry:example",
    registryDependencies: ["slash-command-suggestions"],
    files: [
      {
        path: "examples/SlashCommandSuggestionsDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SpoilerDemo",
    type: "registry:example",
    registryDependencies: ["spoiler"],
    files: [
      {
        path: "examples/SpoilerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "StageBannerDemo",
    type: "registry:example",
    registryDependencies: ["stage-banner"],
    files: [
      {
        path: "examples/StageBannerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "StatusIndicatorDemo",
    type: "registry:example",
    registryDependencies: ["status-indicator"],
    files: [
      {
        path: "examples/StatusIndicatorDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TabsDemo",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [
      {
        path: "examples/TabsDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TimelineDemo",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: [
      {
        path: "examples/TimelineDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ToastDemo",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: [
      {
        path: "examples/ToastDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TokenFieldDemo",
    type: "registry:example",
    registryDependencies: ["token-field"],
    files: [
      {
        path: "examples/TokenFieldDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TooltipDemo",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    files: [
      {
        path: "examples/TooltipDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TypingIndicatorDemo",
    type: "registry:example",
    registryDependencies: ["typing-indicator"],
    files: [
      {
        path: "examples/TypingIndicatorDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "UserProfileDemo",
    type: "registry:example",
    registryDependencies: ["user-profile"],
    files: [
      {
        path: "examples/UserProfileDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "V2ContainerDemo",
    type: "registry:example",
    registryDependencies: ["v2-container"],
    files: [
      {
        path: "examples/V2ContainerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "VoiceChannelDemo",
    type: "registry:example",
    registryDependencies: ["voice-channel"],
    files: [
      {
        path: "examples/VoiceChannelDemo.vue",
        type: "registry:example",
      },
    ],
  },
]
