import {
  defineConfig,
  minimal2023Preset,
} from "@vite-pwa/assets-generator/config"

/*
 * Every icon an installed app is asked for, rasterised from one source.
 *
 * The source is not `favicon.svg`: that one is drawn in the `Canvas` and
 * `CanvasText` system colours so it follows the reader's theme, which a
 * rasteriser cannot resolve. An icon on somebody's home screen has to carry
 * its own colours, so `pwa-icon.svg` states them.
 *
 * The outputs land beside the source in `public/` and are generated by the
 * build, not committed — they are derived files, and reviewing a binary diff
 * of a resized PNG tells nobody anything.
 */
export default defineConfig({
  preset: minimal2023Preset,
  images: ["public/pwa-icon.svg"],
  headLinkOptions: { preset: "2023" },
})
