import {
  defineConfig,
  minimal2023Preset,
} from "@vite-pwa/assets-generator/config"

/*
 * Every icon an installed app is asked for, rasterised from one source.
 *
 * The source draws the same mark the site header wears, but in stated colours
 * rather than `currentColor`: an icon on somebody's home screen sits on a
 * background this site does not choose, so it cannot inherit one.
 *
 * The outputs land beside the source in `public/` and are generated by the
 * build, not committed — they are derived files, and reviewing a binary diff
 * of a resized PNG tells nobody anything.
 */
export default defineConfig({
  preset: minimal2023Preset,
  images: ["public/pwa-icon.svg"],
  headLinkOptions: { preset: "2023" },
})
