// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import { defineAsyncComponent } from "vue"

// Consumers (e.g. app/pages/index.vue) read entries through a local
// `Record<string, unknown>` binding, which requires this contract to carry
// its own index signature — kept to the concrete value types below rather
// than `unknown`/`any` so it stays a real contract instead of an escape hatch.
interface RegistryIndexEntry {
  [key: string]:
    | string
    | string[]
    | ReturnType<typeof defineAsyncComponent>
    | undefined
  name: string
  type: string
  registryDependencies: string[]
  files: string[]
  component?: ReturnType<typeof defineAsyncComponent>
}

// Keys are the registry component/example names; built via `Object.fromEntries`
// (instead of a `Record<string, any>` literal) so the lookup map stays
// indexable by an arbitrary string without widening away the entry type.
const registryIndexEntries: Array<[string, RegistryIndexEntry]> = [
  [
    "action-row",
    {
      name: "action-row",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        "registry/bases/newt/ui/action-row/ActionRow.vue",
        "registry/bases/newt/ui/action-row/index.ts",
      ],
    },
  ],
  [
    "app-launcher",
    {
      name: "app-launcher",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/app-launcher/AppLauncher.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherHandle.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherHeader.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherBack.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherSearch.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherSearchInput.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherBody.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherSection.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherSectionHeader.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherSectionTitle.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherViewMore.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherList.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherItem.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherItemIcon.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherRecents.vue",
        "registry/bases/newt/ui/app-launcher/AppLauncherRecent.vue",
        "registry/bases/newt/ui/app-launcher/index.ts",
      ],
    },
  ],
  [
    "attachment",
    {
      name: "attachment",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        "registry/bases/newt/ui/attachment/Attachment.vue",
        "registry/bases/newt/ui/attachment/AttachmentIcon.vue",
        "registry/bases/newt/ui/attachment/AttachmentMeta.vue",
        "registry/bases/newt/ui/attachment/AttachmentName.vue",
        "registry/bases/newt/ui/attachment/AttachmentSize.vue",
        "registry/bases/newt/ui/attachment/index.ts",
      ],
    },
  ],
  [
    "avatar",
    {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/avatar/Avatar.vue",
        "registry/bases/newt/ui/avatar/AvatarImage.vue",
        "registry/bases/newt/ui/avatar/AvatarFallback.vue",
        "registry/bases/newt/ui/avatar/index.ts",
      ],
    },
  ],
  [
    "badge",
    {
      name: "badge",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/badge/Badge.vue",
        "registry/bases/newt/ui/badge/index.ts",
      ],
    },
  ],
  [
    "bot-command-card",
    {
      name: "bot-command-card",
      type: "registry:ui",
      registryDependencies: ["badge"],
      files: [
        "registry/bases/newt/ui/bot-command-card/BotCommandCard.vue",
        "registry/bases/newt/ui/bot-command-card/BotCommandCardHeader.vue",
        "registry/bases/newt/ui/bot-command-card/BotCommandCardName.vue",
        "registry/bases/newt/ui/bot-command-card/BotCommandCardDescription.vue",
        "registry/bases/newt/ui/bot-command-card/BotCommandCardOptions.vue",
        "registry/bases/newt/ui/bot-command-card/BotCommandCardOption.vue",
        "registry/bases/newt/ui/bot-command-card/index.ts",
      ],
    },
  ],
  [
    "button",
    {
      name: "button",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/button/Button.vue",
        "registry/bases/newt/ui/button/index.ts",
      ],
    },
  ],
  [
    "card",
    {
      name: "card",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/card/Card.vue",
        "registry/bases/newt/ui/card/CardTitle.vue",
        "registry/bases/newt/ui/card/CardDescription.vue",
        "registry/bases/newt/ui/card/index.ts",
      ],
    },
  ],
  [
    "channel-header",
    {
      name: "channel-header",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/channel-header/ChannelHeader.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderInfo.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderIcon.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderName.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderDivider.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderTopic.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderToolbar.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderAction.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderSearch.vue",
        "registry/bases/newt/ui/channel-header/ChannelHeaderOnline.vue",
        "registry/bases/newt/ui/channel-header/index.ts",
      ],
    },
  ],
  [
    "channel-info",
    {
      name: "channel-info",
      type: "registry:ui",
      registryDependencies: ["tabs"],
      files: [
        "registry/bases/newt/ui/channel-info/ChannelInfo.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoToolbar.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoActions.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoAction.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoIdentity.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoIcon.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoName.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoType.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoPanel.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoEmpty.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoEmptyIcon.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoEmptyTitle.vue",
        "registry/bases/newt/ui/channel-info/ChannelInfoEmptyBody.vue",
        "registry/bases/newt/ui/channel-info/index.ts",
      ],
    },
  ],
  [
    "channel-topic",
    {
      name: "channel-topic",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/channel-topic/ChannelTopic.vue",
        "registry/bases/newt/ui/channel-topic/ChannelTopicIcon.vue",
        "registry/bases/newt/ui/channel-topic/ChannelTopicName.vue",
        "registry/bases/newt/ui/channel-topic/ChannelTopicDivider.vue",
        "registry/bases/newt/ui/channel-topic/ChannelTopicDescription.vue",
        "registry/bases/newt/ui/channel-topic/index.ts",
      ],
    },
  ],
  [
    "channel-welcome",
    {
      name: "channel-welcome",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/channel-welcome/ChannelWelcome.vue",
        "registry/bases/newt/ui/channel-welcome/ChannelWelcomeIcon.vue",
        "registry/bases/newt/ui/channel-welcome/ChannelWelcomeTitle.vue",
        "registry/bases/newt/ui/channel-welcome/ChannelWelcomeDescription.vue",
        "registry/bases/newt/ui/channel-welcome/ChannelWelcomeAction.vue",
        "registry/bases/newt/ui/channel-welcome/ChannelWelcomeDate.vue",
        "registry/bases/newt/ui/channel-welcome/index.ts",
      ],
    },
  ],
  [
    "chat",
    {
      name: "chat",
      type: "registry:ui",
      registryDependencies: ["scrollbar", "message-list", "message-composer"],
      files: [
        "registry/bases/newt/ui/chat/Chat.vue",
        "registry/bases/newt/ui/chat/ChatBody.vue",
        "registry/bases/newt/ui/chat/ChatFooter.vue",
        "registry/bases/newt/ui/chat/index.ts",
      ],
    },
  ],
  [
    "chat-window",
    {
      name: "chat-window",
      type: "registry:block",
      registryDependencies: [
        "channel-header",
        "chat",
        "message-list",
        "message-group",
        "message-composer",
        "avatar",
      ],
      files: [
        "registry/bases/newt/blocks/chat-window/ChatWindow.vue",
        "registry/bases/newt/blocks/chat-window/types.ts",
        "registry/bases/newt/blocks/chat-window/index.ts",
      ],
    },
  ],
  [
    "code-block",
    {
      name: "code-block",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/code-block/CodeBlock.vue",
        "registry/bases/newt/ui/code-block/CodeToken.vue",
        "registry/bases/newt/ui/code-block/index.ts",
      ],
    },
  ],
  [
    "command-panel",
    {
      name: "command-panel",
      type: "registry:block",
      registryDependencies: ["slash-command-suggestions", "bot-command-card"],
      files: [
        "registry/bases/newt/blocks/command-panel/CommandPanel.vue",
        "registry/bases/newt/blocks/command-panel/types.ts",
        "registry/bases/newt/blocks/command-panel/index.ts",
      ],
    },
  ],
  [
    "context-menu",
    {
      name: "context-menu",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/context-menu/ContextMenu.vue",
        "registry/bases/newt/ui/context-menu/ContextMenuItem.vue",
        "registry/bases/newt/ui/context-menu/ContextMenuShortcut.vue",
        "registry/bases/newt/ui/context-menu/ContextMenuDivider.vue",
        "registry/bases/newt/ui/context-menu/index.ts",
      ],
    },
  ],
  [
    "cooldown-bar",
    {
      name: "cooldown-bar",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/cooldown-bar/CooldownBar.vue",
        "registry/bases/newt/ui/cooldown-bar/CooldownBarLabel.vue",
        "registry/bases/newt/ui/cooldown-bar/CooldownBarValue.vue",
        "registry/bases/newt/ui/cooldown-bar/CooldownBarTrack.vue",
        "registry/bases/newt/ui/cooldown-bar/index.ts",
      ],
    },
  ],
  [
    "direction",
    {
      name: "direction",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/direction/DirectionProvider.vue",
        "registry/bases/newt/ui/direction/useDirection.ts",
        "registry/bases/newt/ui/direction/index.ts",
      ],
    },
  ],
  [
    "divider",
    {
      name: "divider",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/divider/Divider.vue",
        "registry/bases/newt/ui/divider/index.ts",
      ],
    },
  ],
  [
    "dropdown",
    {
      name: "dropdown",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/dropdown/Dropdown.vue",
        "registry/bases/newt/ui/dropdown/DropdownItem.vue",
        "registry/bases/newt/ui/dropdown/DropdownIcon.vue",
        "registry/bases/newt/ui/dropdown/DropdownContent.vue",
        "registry/bases/newt/ui/dropdown/DropdownLabel.vue",
        "registry/bases/newt/ui/dropdown/DropdownDescription.vue",
        "registry/bases/newt/ui/dropdown/DropdownDivider.vue",
        "registry/bases/newt/ui/dropdown/index.ts",
      ],
    },
  ],
  [
    "embed",
    {
      name: "embed",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/embed/Embed.vue",
        "registry/bases/newt/ui/embed/EmbedAuthor.vue",
        "registry/bases/newt/ui/embed/EmbedAuthorIcon.vue",
        "registry/bases/newt/ui/embed/EmbedAuthorName.vue",
        "registry/bases/newt/ui/embed/EmbedEyebrow.vue",
        "registry/bases/newt/ui/embed/EmbedTitle.vue",
        "registry/bases/newt/ui/embed/EmbedDescription.vue",
        "registry/bases/newt/ui/embed/EmbedFields.vue",
        "registry/bases/newt/ui/embed/EmbedField.vue",
        "registry/bases/newt/ui/embed/EmbedFieldName.vue",
        "registry/bases/newt/ui/embed/EmbedFieldValue.vue",
        "registry/bases/newt/ui/embed/EmbedFooter.vue",
        "registry/bases/newt/ui/embed/EmbedFooterIcon.vue",
        "registry/bases/newt/ui/embed/EmbedFooterSeparator.vue",
        "registry/bases/newt/ui/embed/EmbedTimestamp.vue",
        "registry/bases/newt/ui/embed/index.ts",
      ],
    },
  ],
  [
    "empty-state",
    {
      name: "empty-state",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/empty-state/EmptyState.vue",
        "registry/bases/newt/ui/empty-state/EmptyStateIcon.vue",
        "registry/bases/newt/ui/empty-state/EmptyStateTitle.vue",
        "registry/bases/newt/ui/empty-state/EmptyStateDescription.vue",
        "registry/bases/newt/ui/empty-state/index.ts",
      ],
    },
  ],
  [
    "form-fields",
    {
      name: "form-fields",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/form-fields/Field.vue",
        "registry/bases/newt/ui/form-fields/Label.vue",
        "registry/bases/newt/ui/form-fields/Input.vue",
        "registry/bases/newt/ui/form-fields/Textarea.vue",
        "registry/bases/newt/ui/form-fields/Select.vue",
        "registry/bases/newt/ui/form-fields/FieldHelp.vue",
        "registry/bases/newt/ui/form-fields/Switch.vue",
        "registry/bases/newt/ui/form-fields/Checkbox.vue",
        "registry/bases/newt/ui/form-fields/index.ts",
      ],
    },
  ],
  [
    "inline-code",
    {
      name: "inline-code",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/inline-code/InlineCode.vue",
        "registry/bases/newt/ui/inline-code/index.ts",
      ],
    },
  ],
  [
    "invite",
    {
      name: "invite",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        "registry/bases/newt/ui/invite/Invite.vue",
        "registry/bases/newt/ui/invite/InviteEyebrow.vue",
        "registry/bases/newt/ui/invite/InviteBody.vue",
        "registry/bases/newt/ui/invite/InviteIcon.vue",
        "registry/bases/newt/ui/invite/InviteInfo.vue",
        "registry/bases/newt/ui/invite/InviteName.vue",
        "registry/bases/newt/ui/invite/InviteCounts.vue",
        "registry/bases/newt/ui/invite/InviteCount.vue",
        "registry/bases/newt/ui/invite/index.ts",
      ],
    },
  ],
  [
    "kbd-tag",
    {
      name: "kbd-tag",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/kbd-tag/KbdTag.vue",
        "registry/bases/newt/ui/kbd-tag/index.ts",
      ],
    },
  ],
  [
    "member-list",
    {
      name: "member-list",
      type: "registry:ui",
      registryDependencies: ["avatar", "status-indicator", "role-tag"],
      files: [
        "registry/bases/newt/ui/member-list/MemberList.vue",
        "registry/bases/newt/ui/member-list/MemberListSection.vue",
        "registry/bases/newt/ui/member-list/MemberListHeading.vue",
        "registry/bases/newt/ui/member-list/MemberListItem.vue",
        "registry/bases/newt/ui/member-list/MemberListInfo.vue",
        "registry/bases/newt/ui/member-list/MemberListNameRow.vue",
        "registry/bases/newt/ui/member-list/MemberListName.vue",
        "registry/bases/newt/ui/member-list/MemberListAppTag.vue",
        "registry/bases/newt/ui/member-list/MemberListRole.vue",
        "registry/bases/newt/ui/member-list/index.ts",
      ],
    },
  ],
  [
    "mention",
    {
      name: "mention",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/mention/Mention.vue",
        "registry/bases/newt/ui/mention/index.ts",
      ],
    },
  ],
  [
    "message-composer",
    {
      name: "message-composer",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/message-composer/MessageComposer.vue",
        "registry/bases/newt/ui/message-composer/index.ts",
      ],
    },
  ],
  [
    "message-group",
    {
      name: "message-group",
      type: "registry:ui",
      registryDependencies: [
        "avatar",
        "reaction",
        "reply-preview",
        "status-indicator",
      ],
      files: [
        "registry/bases/newt/ui/message-group/MessageGroup.vue",
        "registry/bases/newt/ui/message-group/MessageGroupAvatar.vue",
        "registry/bases/newt/ui/message-group/MessageGroupReply.vue",
        "registry/bases/newt/ui/message-group/MessageGroupBody.vue",
        "registry/bases/newt/ui/message-group/MessageGroupHeader.vue",
        "registry/bases/newt/ui/message-group/MessageGroupAuthor.vue",
        "registry/bases/newt/ui/message-group/MessageGroupBotTag.vue",
        "registry/bases/newt/ui/message-group/MessageGroupTime.vue",
        "registry/bases/newt/ui/message-group/MessageGroupContent.vue",
        "registry/bases/newt/ui/message-group/MessageGroupReactions.vue",
        "registry/bases/newt/ui/message-group/MessageGroupEphemeralNotice.vue",
        "registry/bases/newt/ui/message-group/MessageGroupEphemeralAction.vue",
        "registry/bases/newt/ui/message-group/index.ts",
      ],
    },
  ],
  [
    "message-list",
    {
      name: "message-list",
      type: "registry:ui",
      registryDependencies: ["message-group"],
      files: [
        "registry/bases/newt/ui/message-list/MessageList.vue",
        "registry/bases/newt/ui/message-list/index.ts",
      ],
    },
  ],
  [
    "modal",
    {
      name: "modal",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        "registry/bases/newt/ui/modal/Modal.vue",
        "registry/bases/newt/ui/modal/ModalHeader.vue",
        "registry/bases/newt/ui/modal/ModalBody.vue",
        "registry/bases/newt/ui/modal/ModalFooter.vue",
        "registry/bases/newt/ui/modal/ModalClose.vue",
        "registry/bases/newt/ui/modal/index.ts",
      ],
    },
  ],
  [
    "notif-badge",
    {
      name: "notif-badge",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: [
        "registry/bases/newt/ui/notif-badge/NotifBadge.vue",
        "registry/bases/newt/ui/notif-badge/index.ts",
      ],
    },
  ],
  [
    "pagination",
    {
      name: "pagination",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        "registry/bases/newt/ui/pagination/Pagination.vue",
        "registry/bases/newt/ui/pagination/PaginationButton.vue",
        "registry/bases/newt/ui/pagination/PaginationEllipsis.vue",
        "registry/bases/newt/ui/pagination/LoadMore.vue",
        "registry/bases/newt/ui/pagination/index.ts",
      ],
    },
  ],
  [
    "permission",
    {
      name: "permission",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/permission/Permission.vue",
        "registry/bases/newt/ui/permission/PermissionInfo.vue",
        "registry/bases/newt/ui/permission/PermissionName.vue",
        "registry/bases/newt/ui/permission/PermissionDescription.vue",
        "registry/bases/newt/ui/permission/PermissionStates.vue",
        "registry/bases/newt/ui/permission/index.ts",
      ],
    },
  ],
  [
    "progress",
    {
      name: "progress",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/progress/Progress.vue",
        "registry/bases/newt/ui/progress/ProgressLabel.vue",
        "registry/bases/newt/ui/progress/index.ts",
      ],
    },
  ],
  [
    "radio",
    {
      name: "radio",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/radio/Radio.vue",
        "registry/bases/newt/ui/radio/RadioGroup.vue",
        "registry/bases/newt/ui/radio/useRadioGroup.ts",
        "registry/bases/newt/ui/radio/index.ts",
      ],
    },
  ],
  [
    "reaction",
    {
      name: "reaction",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/reaction/Reaction.vue",
        "registry/bases/newt/ui/reaction/ReactionGroup.vue",
        "registry/bases/newt/ui/reaction/index.ts",
      ],
    },
  ],
  [
    "reply-preview",
    {
      name: "reply-preview",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/reply-preview/ReplyPreview.vue",
        "registry/bases/newt/ui/reply-preview/ReplyPreviewAvatar.vue",
        "registry/bases/newt/ui/reply-preview/ReplyPreviewAuthor.vue",
        "registry/bases/newt/ui/reply-preview/ReplyPreviewText.vue",
        "registry/bases/newt/ui/reply-preview/ReplyPreviewAction.vue",
        "registry/bases/newt/ui/reply-preview/ReplyPreviewCommand.vue",
        "registry/bases/newt/ui/reply-preview/index.ts",
      ],
    },
  ],
  [
    "role-tag",
    {
      name: "role-tag",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/role-tag/RoleTag.vue",
        "registry/bases/newt/ui/role-tag/RoleTagDot.vue",
        "registry/bases/newt/ui/role-tag/index.ts",
      ],
    },
  ],
  [
    "scrollbar",
    {
      name: "scrollbar",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/scrollbar/ScrollArea.vue",
        "registry/bases/newt/ui/scrollbar/index.ts",
      ],
    },
  ],
  [
    "select-menu",
    {
      name: "select-menu",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/select-menu/SelectMenu.vue",
        "registry/bases/newt/ui/select-menu/index.ts",
      ],
    },
  ],
  [
    "server-banner",
    {
      name: "server-banner",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        "registry/bases/newt/ui/server-banner/ServerBanner.vue",
        "registry/bases/newt/ui/server-banner/ServerBannerIcon.vue",
        "registry/bases/newt/ui/server-banner/ServerBannerInfo.vue",
        "registry/bases/newt/ui/server-banner/ServerBannerName.vue",
        "registry/bases/newt/ui/server-banner/ServerBannerMeta.vue",
        "registry/bases/newt/ui/server-banner/ServerBannerMetaItem.vue",
        "registry/bases/newt/ui/server-banner/index.ts",
      ],
    },
  ],
  [
    "server-sidebar",
    {
      name: "server-sidebar",
      type: "registry:block",
      registryDependencies: [
        "server-banner",
        "voice-channel",
        "member-list",
        "status-indicator",
        "avatar",
      ],
      files: [
        "registry/bases/newt/blocks/server-sidebar/ServerSidebar.vue",
        "registry/bases/newt/blocks/server-sidebar/types.ts",
        "registry/bases/newt/blocks/server-sidebar/index.ts",
      ],
    },
  ],
  [
    "skeleton",
    {
      name: "skeleton",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/skeleton/Skeleton.vue",
        "registry/bases/newt/ui/skeleton/index.ts",
      ],
    },
  ],
  [
    "slash-command",
    {
      name: "slash-command",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/slash-command/SlashCommand.vue",
        "registry/bases/newt/ui/slash-command/index.ts",
      ],
    },
  ],
  [
    "slash-command-suggestions",
    {
      name: "slash-command-suggestions",
      type: "registry:ui",
      registryDependencies: ["slash-command"],
      files: [
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestions.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestionsRail.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestionsRailItem.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestionsList.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestionsHeader.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestionGroup.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandAppIcon.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestion.vue",
        "registry/bases/newt/ui/slash-command-suggestions/SlashCommandSuggestionMatched.vue",
        "registry/bases/newt/ui/slash-command-suggestions/index.ts",
      ],
    },
  ],
  [
    "spoiler",
    {
      name: "spoiler",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/spoiler/Spoiler.vue",
        "registry/bases/newt/ui/spoiler/index.ts",
      ],
    },
  ],
  [
    "stage-banner",
    {
      name: "stage-banner",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/stage-banner/StageBanner.vue",
        "registry/bases/newt/ui/stage-banner/StageBannerDot.vue",
        "registry/bases/newt/ui/stage-banner/StageBannerAction.vue",
        "registry/bases/newt/ui/stage-banner/StageBannerClose.vue",
        "registry/bases/newt/ui/stage-banner/index.ts",
      ],
    },
  ],
  [
    "status-indicator",
    {
      name: "status-indicator",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: [
        "registry/bases/newt/ui/status-indicator/StatusIndicator.vue",
        "registry/bases/newt/ui/status-indicator/StatusDot.vue",
        "registry/bases/newt/ui/status-indicator/index.ts",
      ],
    },
  ],
  [
    "tabs",
    {
      name: "tabs",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/tabs/Tabs.vue",
        "registry/bases/newt/ui/tabs/TabsTrigger.vue",
        "registry/bases/newt/ui/tabs/TabsContent.vue",
        "registry/bases/newt/ui/tabs/index.ts",
      ],
    },
  ],
  [
    "timeline",
    {
      name: "timeline",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/timeline/Timeline.vue",
        "registry/bases/newt/ui/timeline/TimelineItem.vue",
        "registry/bases/newt/ui/timeline/TimelineDot.vue",
        "registry/bases/newt/ui/timeline/TimelineContent.vue",
        "registry/bases/newt/ui/timeline/TimelineTitle.vue",
        "registry/bases/newt/ui/timeline/TimelineMeta.vue",
        "registry/bases/newt/ui/timeline/index.ts",
      ],
    },
  ],
  [
    "toast",
    {
      name: "toast",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/toast/Toast.vue",
        "registry/bases/newt/ui/toast/ToastIcon.vue",
        "registry/bases/newt/ui/toast/ToastContent.vue",
        "registry/bases/newt/ui/toast/ToastTitle.vue",
        "registry/bases/newt/ui/toast/ToastDescription.vue",
        "registry/bases/newt/ui/toast/ToastClose.vue",
        "registry/bases/newt/ui/toast/index.ts",
      ],
    },
  ],
  [
    "token-field",
    {
      name: "token-field",
      type: "registry:ui",
      registryDependencies: ["form-fields", "button"],
      files: [
        "registry/bases/newt/ui/token-field/TokenField.vue",
        "registry/bases/newt/ui/token-field/index.ts",
      ],
    },
  ],
  [
    "tooltip",
    {
      name: "tooltip",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/tooltip/Tooltip.vue",
        "registry/bases/newt/ui/tooltip/TooltipTrigger.vue",
        "registry/bases/newt/ui/tooltip/TooltipContent.vue",
        "registry/bases/newt/ui/tooltip/index.ts",
      ],
    },
  ],
  [
    "typeset",
    {
      name: "typeset",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/typeset/Typeset.vue",
        "registry/bases/newt/ui/typeset/index.ts",
      ],
    },
  ],
  [
    "typing-indicator",
    {
      name: "typing-indicator",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/typing-indicator/TypingIndicator.vue",
        "registry/bases/newt/ui/typing-indicator/TypingIndicatorDots.vue",
        "registry/bases/newt/ui/typing-indicator/index.ts",
      ],
    },
  ],
  [
    "user-profile",
    {
      name: "user-profile",
      type: "registry:ui",
      registryDependencies: [
        "avatar",
        "status-indicator",
        "role-tag",
        "button",
      ],
      files: [
        "registry/bases/newt/ui/user-profile/UserProfile.vue",
        "registry/bases/newt/ui/user-profile/UserProfileBanner.vue",
        "registry/bases/newt/ui/user-profile/UserProfileHead.vue",
        "registry/bases/newt/ui/user-profile/UserProfileActions.vue",
        "registry/bases/newt/ui/user-profile/UserProfileAvatar.vue",
        "registry/bases/newt/ui/user-profile/UserProfileName.vue",
        "registry/bases/newt/ui/user-profile/UserProfileHandle.vue",
        "registry/bases/newt/ui/user-profile/UserProfileDivider.vue",
        "registry/bases/newt/ui/user-profile/UserProfileBody.vue",
        "registry/bases/newt/ui/user-profile/UserProfileSectionLabel.vue",
        "registry/bases/newt/ui/user-profile/UserProfileBio.vue",
        "registry/bases/newt/ui/user-profile/UserProfileRoles.vue",
        "registry/bases/newt/ui/user-profile/index.ts",
      ],
    },
  ],
  [
    "v2-container",
    {
      name: "v2-container",
      type: "registry:ui",
      registryDependencies: [],
      files: [
        "registry/bases/newt/ui/v2-container/V2Container.vue",
        "registry/bases/newt/ui/v2-container/index.ts",
      ],
    },
  ],
  [
    "voice-channel",
    {
      name: "voice-channel",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: [
        "registry/bases/newt/ui/voice-channel/VoiceChannel.vue",
        "registry/bases/newt/ui/voice-channel/VoiceChannelHeader.vue",
        "registry/bases/newt/ui/voice-channel/VoiceChannelIcon.vue",
        "registry/bases/newt/ui/voice-channel/VoiceChannelMembers.vue",
        "registry/bases/newt/ui/voice-channel/VoiceChannelMember.vue",
        "registry/bases/newt/ui/voice-channel/VoiceChannelMemberIcons.vue",
        "registry/bases/newt/ui/voice-channel/index.ts",
      ],
    },
  ],
  [
    "ActionRowDemo",
    {
      name: "ActionRowDemo",
      type: "registry:example",
      registryDependencies: ["action-row"],
      files: ["registry/bases/newt/examples/ActionRowDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ActionRowDemo.vue")
      ),
    },
  ],
  [
    "AppLauncherDemo",
    {
      name: "AppLauncherDemo",
      type: "registry:example",
      registryDependencies: ["app-launcher"],
      files: ["registry/bases/newt/examples/AppLauncherDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/AppLauncherDemo.vue")
      ),
    },
  ],
  [
    "AttachmentDemo",
    {
      name: "AttachmentDemo",
      type: "registry:example",
      registryDependencies: ["attachment"],
      files: ["registry/bases/newt/examples/AttachmentDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/AttachmentDemo.vue")
      ),
    },
  ],
  [
    "AvatarDemo",
    {
      name: "AvatarDemo",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: ["registry/bases/newt/examples/AvatarDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/AvatarDemo.vue")
      ),
    },
  ],
  [
    "BadgeDemo",
    {
      name: "BadgeDemo",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: ["registry/bases/newt/examples/BadgeDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/BadgeDemo.vue")
      ),
    },
  ],
  [
    "BotCommandCardDemo",
    {
      name: "BotCommandCardDemo",
      type: "registry:example",
      registryDependencies: ["bot-command-card"],
      files: ["registry/bases/newt/examples/BotCommandCardDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/BotCommandCardDemo.vue")
      ),
    },
  ],
  [
    "ButtonDemo",
    {
      name: "ButtonDemo",
      type: "registry:example",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/examples/ButtonDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ButtonDemo.vue")
      ),
    },
  ],
  [
    "CardDemo",
    {
      name: "CardDemo",
      type: "registry:example",
      registryDependencies: ["card"],
      files: ["registry/bases/newt/examples/CardDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/CardDemo.vue")
      ),
    },
  ],
  [
    "ChannelHeaderDemo",
    {
      name: "ChannelHeaderDemo",
      type: "registry:example",
      registryDependencies: ["channel-header"],
      files: ["registry/bases/newt/examples/ChannelHeaderDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ChannelHeaderDemo.vue")
      ),
    },
  ],
  [
    "ChannelInfoDemo",
    {
      name: "ChannelInfoDemo",
      type: "registry:example",
      registryDependencies: ["channel-info"],
      files: ["registry/bases/newt/examples/ChannelInfoDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ChannelInfoDemo.vue")
      ),
    },
  ],
  [
    "ChannelTopicDemo",
    {
      name: "ChannelTopicDemo",
      type: "registry:example",
      registryDependencies: ["channel-topic"],
      files: ["registry/bases/newt/examples/ChannelTopicDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ChannelTopicDemo.vue")
      ),
    },
  ],
  [
    "ChannelWelcomeDemo",
    {
      name: "ChannelWelcomeDemo",
      type: "registry:example",
      registryDependencies: ["channel-welcome"],
      files: ["registry/bases/newt/examples/ChannelWelcomeDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ChannelWelcomeDemo.vue")
      ),
    },
  ],
  [
    "ChatDemo",
    {
      name: "ChatDemo",
      type: "registry:example",
      registryDependencies: ["chat"],
      files: ["registry/bases/newt/examples/ChatDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ChatDemo.vue")
      ),
    },
  ],
  [
    "ChatWindowDemo",
    {
      name: "ChatWindowDemo",
      type: "registry:example",
      registryDependencies: ["chat-window"],
      files: ["registry/bases/newt/examples/ChatWindowDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ChatWindowDemo.vue")
      ),
    },
  ],
  [
    "CodeBlockDemo",
    {
      name: "CodeBlockDemo",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: ["registry/bases/newt/examples/CodeBlockDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/CodeBlockDemo.vue")
      ),
    },
  ],
  [
    "CommandPanelDemo",
    {
      name: "CommandPanelDemo",
      type: "registry:example",
      registryDependencies: ["command-panel"],
      files: ["registry/bases/newt/examples/CommandPanelDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/CommandPanelDemo.vue")
      ),
    },
  ],
  [
    "ContextMenuDemo",
    {
      name: "ContextMenuDemo",
      type: "registry:example",
      registryDependencies: ["context-menu"],
      files: ["registry/bases/newt/examples/ContextMenuDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ContextMenuDemo.vue")
      ),
    },
  ],
  [
    "CooldownBarDemo",
    {
      name: "CooldownBarDemo",
      type: "registry:example",
      registryDependencies: ["cooldown-bar"],
      files: ["registry/bases/newt/examples/CooldownBarDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/CooldownBarDemo.vue")
      ),
    },
  ],
  [
    "DirectionDemo",
    {
      name: "DirectionDemo",
      type: "registry:example",
      registryDependencies: ["direction"],
      files: ["registry/bases/newt/examples/DirectionDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/DirectionDemo.vue")
      ),
    },
  ],
  [
    "DividerDemo",
    {
      name: "DividerDemo",
      type: "registry:example",
      registryDependencies: ["divider"],
      files: ["registry/bases/newt/examples/DividerDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/DividerDemo.vue")
      ),
    },
  ],
  [
    "DropdownDemo",
    {
      name: "DropdownDemo",
      type: "registry:example",
      registryDependencies: ["dropdown"],
      files: ["registry/bases/newt/examples/DropdownDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/DropdownDemo.vue")
      ),
    },
  ],
  [
    "EmbedDemo",
    {
      name: "EmbedDemo",
      type: "registry:example",
      registryDependencies: ["embed"],
      files: ["registry/bases/newt/examples/EmbedDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/EmbedDemo.vue")
      ),
    },
  ],
  [
    "EmptyStateDemo",
    {
      name: "EmptyStateDemo",
      type: "registry:example",
      registryDependencies: ["empty-state"],
      files: ["registry/bases/newt/examples/EmptyStateDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/EmptyStateDemo.vue")
      ),
    },
  ],
  [
    "FormFieldsDemo",
    {
      name: "FormFieldsDemo",
      type: "registry:example",
      registryDependencies: ["form-fields"],
      files: ["registry/bases/newt/examples/FormFieldsDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/FormFieldsDemo.vue")
      ),
    },
  ],
  [
    "InlineCodeDemo",
    {
      name: "InlineCodeDemo",
      type: "registry:example",
      registryDependencies: ["inline-code"],
      files: ["registry/bases/newt/examples/InlineCodeDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/InlineCodeDemo.vue")
      ),
    },
  ],
  [
    "InviteDemo",
    {
      name: "InviteDemo",
      type: "registry:example",
      registryDependencies: ["invite"],
      files: ["registry/bases/newt/examples/InviteDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/InviteDemo.vue")
      ),
    },
  ],
  [
    "KbdTagDemo",
    {
      name: "KbdTagDemo",
      type: "registry:example",
      registryDependencies: ["kbd-tag"],
      files: ["registry/bases/newt/examples/KbdTagDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/KbdTagDemo.vue")
      ),
    },
  ],
  [
    "MemberListDemo",
    {
      name: "MemberListDemo",
      type: "registry:example",
      registryDependencies: ["member-list"],
      files: ["registry/bases/newt/examples/MemberListDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/MemberListDemo.vue")
      ),
    },
  ],
  [
    "MentionDemo",
    {
      name: "MentionDemo",
      type: "registry:example",
      registryDependencies: ["mention"],
      files: ["registry/bases/newt/examples/MentionDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/MentionDemo.vue")
      ),
    },
  ],
  [
    "MessageComposerDemo",
    {
      name: "MessageComposerDemo",
      type: "registry:example",
      registryDependencies: ["message-composer"],
      files: ["registry/bases/newt/examples/MessageComposerDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/MessageComposerDemo.vue")
      ),
    },
  ],
  [
    "MessageGroupDemo",
    {
      name: "MessageGroupDemo",
      type: "registry:example",
      registryDependencies: ["message-group"],
      files: ["registry/bases/newt/examples/MessageGroupDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/MessageGroupDemo.vue")
      ),
    },
  ],
  [
    "MessageListDemo",
    {
      name: "MessageListDemo",
      type: "registry:example",
      registryDependencies: ["message-list"],
      files: ["registry/bases/newt/examples/MessageListDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/MessageListDemo.vue")
      ),
    },
  ],
  [
    "ModalDemo",
    {
      name: "ModalDemo",
      type: "registry:example",
      registryDependencies: ["modal"],
      files: ["registry/bases/newt/examples/ModalDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ModalDemo.vue")
      ),
    },
  ],
  [
    "NotifBadgeDemo",
    {
      name: "NotifBadgeDemo",
      type: "registry:example",
      registryDependencies: ["notif-badge"],
      files: ["registry/bases/newt/examples/NotifBadgeDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/NotifBadgeDemo.vue")
      ),
    },
  ],
  [
    "PaginationDemo",
    {
      name: "PaginationDemo",
      type: "registry:example",
      registryDependencies: ["pagination"],
      files: ["registry/bases/newt/examples/PaginationDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/PaginationDemo.vue")
      ),
    },
  ],
  [
    "PermissionDemo",
    {
      name: "PermissionDemo",
      type: "registry:example",
      registryDependencies: ["permission"],
      files: ["registry/bases/newt/examples/PermissionDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/PermissionDemo.vue")
      ),
    },
  ],
  [
    "ProgressDemo",
    {
      name: "ProgressDemo",
      type: "registry:example",
      registryDependencies: ["progress"],
      files: ["registry/bases/newt/examples/ProgressDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ProgressDemo.vue")
      ),
    },
  ],
  [
    "RadioDemo",
    {
      name: "RadioDemo",
      type: "registry:example",
      registryDependencies: ["radio"],
      files: ["registry/bases/newt/examples/RadioDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/RadioDemo.vue")
      ),
    },
  ],
  [
    "ReactionDemo",
    {
      name: "ReactionDemo",
      type: "registry:example",
      registryDependencies: ["reaction"],
      files: ["registry/bases/newt/examples/ReactionDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ReactionDemo.vue")
      ),
    },
  ],
  [
    "ReplyPreviewDemo",
    {
      name: "ReplyPreviewDemo",
      type: "registry:example",
      registryDependencies: ["reply-preview"],
      files: ["registry/bases/newt/examples/ReplyPreviewDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ReplyPreviewDemo.vue")
      ),
    },
  ],
  [
    "RoleTagDemo",
    {
      name: "RoleTagDemo",
      type: "registry:example",
      registryDependencies: ["role-tag"],
      files: ["registry/bases/newt/examples/RoleTagDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/RoleTagDemo.vue")
      ),
    },
  ],
  [
    "ScrollbarDemo",
    {
      name: "ScrollbarDemo",
      type: "registry:example",
      registryDependencies: ["scrollbar"],
      files: ["registry/bases/newt/examples/ScrollbarDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ScrollbarDemo.vue")
      ),
    },
  ],
  [
    "SelectMenuDemo",
    {
      name: "SelectMenuDemo",
      type: "registry:example",
      registryDependencies: ["select-menu"],
      files: ["registry/bases/newt/examples/SelectMenuDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/SelectMenuDemo.vue")
      ),
    },
  ],
  [
    "ServerBannerDemo",
    {
      name: "ServerBannerDemo",
      type: "registry:example",
      registryDependencies: ["server-banner"],
      files: ["registry/bases/newt/examples/ServerBannerDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ServerBannerDemo.vue")
      ),
    },
  ],
  [
    "ServerSidebarDemo",
    {
      name: "ServerSidebarDemo",
      type: "registry:example",
      registryDependencies: ["server-sidebar"],
      files: ["registry/bases/newt/examples/ServerSidebarDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ServerSidebarDemo.vue")
      ),
    },
  ],
  [
    "SkeletonDemo",
    {
      name: "SkeletonDemo",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: ["registry/bases/newt/examples/SkeletonDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/SkeletonDemo.vue")
      ),
    },
  ],
  [
    "SlashCommandDemo",
    {
      name: "SlashCommandDemo",
      type: "registry:example",
      registryDependencies: ["slash-command"],
      files: ["registry/bases/newt/examples/SlashCommandDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/SlashCommandDemo.vue")
      ),
    },
  ],
  [
    "SlashCommandSuggestionsDemo",
    {
      name: "SlashCommandSuggestionsDemo",
      type: "registry:example",
      registryDependencies: ["slash-command-suggestions"],
      files: ["registry/bases/newt/examples/SlashCommandSuggestionsDemo.vue"],
      component: defineAsyncComponent(
        () =>
          import("~~/registry/bases/newt/examples/SlashCommandSuggestionsDemo.vue")
      ),
    },
  ],
  [
    "SpoilerDemo",
    {
      name: "SpoilerDemo",
      type: "registry:example",
      registryDependencies: ["spoiler"],
      files: ["registry/bases/newt/examples/SpoilerDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/SpoilerDemo.vue")
      ),
    },
  ],
  [
    "StageBannerDemo",
    {
      name: "StageBannerDemo",
      type: "registry:example",
      registryDependencies: ["stage-banner"],
      files: ["registry/bases/newt/examples/StageBannerDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/StageBannerDemo.vue")
      ),
    },
  ],
  [
    "StatusIndicatorDemo",
    {
      name: "StatusIndicatorDemo",
      type: "registry:example",
      registryDependencies: ["status-indicator"],
      files: ["registry/bases/newt/examples/StatusIndicatorDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/StatusIndicatorDemo.vue")
      ),
    },
  ],
  [
    "TabsDemo",
    {
      name: "TabsDemo",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: ["registry/bases/newt/examples/TabsDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/TabsDemo.vue")
      ),
    },
  ],
  [
    "TimelineDemo",
    {
      name: "TimelineDemo",
      type: "registry:example",
      registryDependencies: ["timeline"],
      files: ["registry/bases/newt/examples/TimelineDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/TimelineDemo.vue")
      ),
    },
  ],
  [
    "ToastDemo",
    {
      name: "ToastDemo",
      type: "registry:example",
      registryDependencies: ["toast"],
      files: ["registry/bases/newt/examples/ToastDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/ToastDemo.vue")
      ),
    },
  ],
  [
    "TokenFieldDemo",
    {
      name: "TokenFieldDemo",
      type: "registry:example",
      registryDependencies: ["token-field"],
      files: ["registry/bases/newt/examples/TokenFieldDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/TokenFieldDemo.vue")
      ),
    },
  ],
  [
    "TooltipDemo",
    {
      name: "TooltipDemo",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: ["registry/bases/newt/examples/TooltipDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/TooltipDemo.vue")
      ),
    },
  ],
  [
    "TypesetDemo",
    {
      name: "TypesetDemo",
      type: "registry:example",
      registryDependencies: ["typeset"],
      files: ["registry/bases/newt/examples/TypesetDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/TypesetDemo.vue")
      ),
    },
  ],
  [
    "TypingIndicatorDemo",
    {
      name: "TypingIndicatorDemo",
      type: "registry:example",
      registryDependencies: ["typing-indicator"],
      files: ["registry/bases/newt/examples/TypingIndicatorDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/TypingIndicatorDemo.vue")
      ),
    },
  ],
  [
    "UserProfileDemo",
    {
      name: "UserProfileDemo",
      type: "registry:example",
      registryDependencies: ["user-profile"],
      files: ["registry/bases/newt/examples/UserProfileDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/UserProfileDemo.vue")
      ),
    },
  ],
  [
    "V2ContainerDemo",
    {
      name: "V2ContainerDemo",
      type: "registry:example",
      registryDependencies: ["v2-container"],
      files: ["registry/bases/newt/examples/V2ContainerDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/V2ContainerDemo.vue")
      ),
    },
  ],
  [
    "VoiceChannelDemo",
    {
      name: "VoiceChannelDemo",
      type: "registry:example",
      registryDependencies: ["voice-channel"],
      files: ["registry/bases/newt/examples/VoiceChannelDemo.vue"],
      component: defineAsyncComponent(
        () => import("~~/registry/bases/newt/examples/VoiceChannelDemo.vue")
      ),
    },
  ],
]

export const Index = {
  default: Object.fromEntries(registryIndexEntries),
}
