// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import { Registry } from "@/registry/schema"

export const ui: Registry = [
  {
    name: "action-row",
    type: "registry:ui",
    title: "Action Row",
    description: "The row of buttons and selects attached under a message.",
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/action-row.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "attachment",
    type: "registry:ui",
    title: "Attachment Card",
    description:
      "File card showing a type icon, file name, size and a download action.",
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/attachment.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "avatar",
    type: "registry:ui",
    title: "Avatar",
    description:
      "A circular user avatar with image support and initials fallback in three sizes.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/avatar.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "badge",
    type: "registry:ui",
    title: "Badge",
    description: "A small pill used to label status, counts or categories.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/badge.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "bot-command-card",
    type: "registry:ui",
    title: "Bot Command Card",
    description:
      "A card documenting a slash command, its owning bot and its typed options.",
    registryDependencies: ["badge"],
    files: [
      {
        path: "ui/bot-command-card.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "button",
    type: "registry:ui",
    title: "Button",
    description:
      "Displays a Discord-styled button with brand, secondary, success, danger, link and icon variants.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/button.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "card",
    type: "registry:ui",
    title: "Card",
    description: "A bordered, elevated panel for grouping related content.",
    files: [
      {
        path: "ui/card.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "channel-topic",
    type: "registry:ui",
    title: "Channel Topic Bar",
    description:
      "A header bar showing the channel name and a truncating topic description.",
    files: [
      {
        path: "ui/channel-topic.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "chat",
    type: "registry:ui",
    title: "Chat",
    description:
      "The channel shell: a scrolling message log with the composer pinned below it.",
    registryDependencies: ["scrollbar", "message-list", "message-composer"],
    files: [
      {
        path: "ui/chat.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "code-block",
    type: "registry:ui",
    title: "Code Block",
    description:
      "A monospace preformatted block with optional syntax-highlight tokens.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/code-block.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "context-menu",
    type: "registry:ui",
    title: "Context Menu",
    description:
      "A floating right-click style menu with items, keyboard shortcuts, dividers and a danger variant.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/context-menu.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "cooldown-bar",
    type: "registry:ui",
    title: "Cooldown Bar",
    description:
      "A slim progress bar with a label and monospace countdown for command cooldowns.",
    files: [
      {
        path: "ui/cooldown-bar.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "divider",
    type: "registry:ui",
    title: "Divider",
    description:
      "A horizontal rule with an optional centered label, spacing steps and a line-less mode.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/divider.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "dropdown",
    type: "registry:ui",
    title: "Dropdown Menu",
    description:
      "A floating menu panel with icon, label and description items that highlight in brand color.",
    files: [
      {
        path: "ui/dropdown.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "embed",
    type: "registry:ui",
    title: "Embed",
    description:
      "A Discord-inspired rich message embed with an accent bar, author, title, description, fields, footer and timestamp.",
    files: [
      {
        path: "ui/embed.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "empty-state",
    type: "registry:ui",
    title: "Empty State",
    description:
      "A centered placeholder with an icon, title, and hint shown when a list or view has no content.",
    files: [
      {
        path: "ui/empty-state.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "form-fields",
    type: "registry:ui",
    title: "Form Fields",
    description:
      "Inputs, textareas, selects, labels, helper text, switches and checkboxes styled for the newt/ui dark theme.",
    files: [
      {
        path: "ui/form-fields.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "inline-code",
    type: "registry:ui",
    title: "Inline Code",
    description: "A monospace pill for code inside a line of message text.",
    files: [
      {
        path: "ui/inline-code.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "kbd-tag",
    type: "registry:ui",
    title: "Keyboard Shortcut Tag",
    description: "A small monospace tag for displaying keyboard shortcuts.",
    files: [
      {
        path: "ui/kbd-tag.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "member-list",
    type: "registry:ui",
    title: "Member List",
    description:
      "A server member sidebar: role sections, presence, coloured names and APP tags.",
    registryDependencies: ["avatar", "status-indicator", "role-tag"],
    files: [
      {
        path: "ui/member-list.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "mention",
    type: "registry:ui",
    title: "Mention Chip",
    description:
      "An inline chip for user, channel, role and app mentions, with an optional avatar.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/mention.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "message-composer",
    type: "registry:ui",
    title: "Message Composer",
    description:
      "The channel input bar: attachment control, text field with combobox hooks, and send.",
    files: [
      {
        path: "ui/message-composer.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "message-group",
    type: "registry:ui",
    title: "Message Group",
    description:
      "A grouped chat message with author, timestamp, reply preview, reactions and an ephemeral state.",
    registryDependencies: [
      "avatar",
      "reaction",
      "reply-preview",
      "status-indicator",
    ],
    files: [
      {
        path: "ui/message-group.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "message-list",
    type: "registry:ui",
    title: "Message List",
    description:
      "The polite live region that logs grouped messages in a channel.",
    registryDependencies: ["message-group"],
    files: [
      {
        path: "ui/message-list.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "modal",
    type: "registry:ui",
    title: "Modal",
    description:
      "A centered dialog over a dimmed overlay that closes on Escape, overlay click or an explicit close control.",
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/modal.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "notif-badge",
    type: "registry:ui",
    title: "Notification Badge",
    description:
      "A small count badge or unread dot for signalling new activity on avatars and channels.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "ui/notif-badge.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "pagination",
    type: "registry:ui",
    title: "Pagination",
    description:
      "Numbered page buttons with previous/next controls, plus a divider-style load-more row.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/pagination.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "permission",
    type: "registry:ui",
    title: "Permission Row",
    description:
      "A settings row with a deny / inherit / allow tri-state toggle.",
    files: [
      {
        path: "ui/permission.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "progress",
    type: "registry:ui",
    title: "Progress Bar",
    description:
      "A gradient progress bar for boosts, uploads and other long-running tasks.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/progress.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "reaction",
    type: "registry:ui",
    title: "Reaction Pill",
    description:
      "A toggleable emoji reaction pill, plus the group that rows them under a message.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/reaction.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "reply-preview",
    type: "registry:ui",
    title: "Reply Preview",
    description:
      'A compact "replying to" bar showing the author, a truncated excerpt, or the slash command that was used.',
    files: [
      {
        path: "ui/reply-preview.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "role-tag",
    type: "registry:ui",
    title: "Role Tag",
    description:
      "A compact bordered tag with a coloured dot for displaying a member's role.",
    files: [
      {
        path: "ui/role-tag.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "scrollbar",
    type: "registry:ui",
    title: "Scrollbar Utility",
    description:
      "Discord-styled scrollbars for any scrollable container, with an optional keyboard-focusable viewport.",
    files: [
      {
        path: "ui/scrollbar.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "select-menu",
    type: "registry:ui",
    title: "Select Menu",
    description:
      "A Discord-inspired string select: combobox trigger, keyboard-driven listbox and a portalled panel.",
    files: [
      {
        path: "ui/select-menu.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "server-banner",
    type: "registry:ui",
    title: "Server Banner",
    description:
      "Invite-style card with a server icon, name, live member counts and a join button.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/server-banner.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    title: "Skeleton Loader",
    description: "A shimmering placeholder shown while content is loading.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/skeleton.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "slash-command",
    type: "registry:ui",
    title: "Slash Command",
    description:
      "An inline /command with its subcommand path and typed options, including the focused one.",
    files: [
      {
        path: "ui/slash-command.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "spoiler",
    type: "registry:ui",
    title: "Spoiler",
    description:
      "Inline text hidden behind a dark block until the reader clicks to reveal it.",
    files: [
      {
        path: "ui/spoiler.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "stage-banner",
    type: "registry:ui",
    title: "Stage Banner",
    description:
      "A full-width announcement strip with a status dot, optional action button and dismiss control.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/stage-banner.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "status-indicator",
    type: "registry:ui",
    title: "Status Indicator",
    description:
      "A presence dot anchored to an avatar, with online, idle, do-not-disturb, offline and streaming states.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "ui/status-indicator.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "tabs",
    type: "registry:ui",
    title: "Tabs",
    description: "A pill-style tab list that switches the active tab on click.",
    files: [
      {
        path: "ui/tabs.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "timeline",
    type: "registry:ui",
    title: "Event Timeline",
    description:
      "A vertical event log with connected status dots, titles and metadata.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/timeline.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "toast",
    type: "registry:ui",
    title: "Toast",
    description:
      "A transient notification with a status icon that auto-dismisses after a timeout or when closed.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/toast.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "token-field",
    type: "registry:ui",
    title: "Token Field",
    description:
      "A read-only, masked monospace input with reveal and copy-to-clipboard actions for secrets such as bot tokens.",
    registryDependencies: ["form-fields", "button"],
    files: [
      {
        path: "ui/token-field.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    title: "Tooltip",
    description:
      "A small floating label that appears above an element on hover or focus.",
    files: [
      {
        path: "ui/tooltip.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "typing-indicator",
    type: "registry:ui",
    title: "Typing Indicator",
    description:
      "Three bouncing dots with a label that signals someone is typing.",
    files: [
      {
        path: "ui/typing-indicator.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "user-profile",
    type: "registry:ui",
    title: "User Profile Popout",
    description:
      "Floating profile card with a banner, overlapping avatar, bio section and role tags.",
    registryDependencies: ["avatar", "status-indicator", "role-tag", "button"],
    files: [
      {
        path: "ui/user-profile.tsx",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "voice-channel",
    type: "registry:ui",
    title: "Voice Channel Row",
    description:
      "A sidebar voice channel row with a collapsible header and the list of connected members.",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "ui/voice-channel.tsx",
        type: "registry:ui",
      },
    ],
  },
]
