// Autogenerated from packages/newt-ui/registry/html/registry.json — the canonical
// BEM root class of each component, shown in the docs section header.
const rootClassEntries = [
  ["button", "newt-btn"],
  ["badge", "newt-badge"],
  ["status-indicator", "newt-status"],
  ["avatar", "newt-avatar"],
  ["embed", "newt-embed"],
  ["card", "newt-card"],
  ["form-fields", "newt-field"],
  ["slash-command", "newt-command"],
  ["tabs", "newt-tabs"],
  ["tooltip", "newt-tooltip"],
  ["modal", "newt-modal"],
  ["toast", "newt-toast"],
  ["code-block", "newt-code"],
  ["reaction", "newt-reaction"],
  ["reply-preview", "newt-reply"],
  ["typing-indicator", "newt-typing"],
  ["progress", "newt-progress"],
  ["member-list", "newt-member"],
  ["role-tag", "newt-role-tag"],
  ["divider", "newt-divider"],
  ["mention", "newt-mention"],
  ["spoiler", "newt-spoiler"],
  ["voice-channel", "newt-voice-channel"],
  ["attachment", "newt-attachment"],
  ["timeline", "newt-timeline"],
  ["permission", "newt-permission"],
  ["token-field", "newt-token-field"],
  ["dropdown", "newt-dropdown"],
  ["skeleton", "newt-skeleton"],
  ["empty-state", "newt-empty-state"],
  ["context-menu", "newt-context-menu"],
  ["server-banner", "newt-server-banner"],
  ["kbd-tag", "newt-kbd"],
  ["cooldown-bar", "newt-cooldown"],
  ["pagination", "newt-pagination"],
  ["stage-banner", "newt-stage-banner"],
  ["scrollbar", "newt-scrollbar"],
  ["channel-topic", "newt-channel-topic"],
  ["notif-badge", "newt-notif-badge"],
  ["user-profile", "newt-profile"],
  ["message-group", "newt-message-group"],
  ["select-menu", "newt-select-menu"],
  ["bot-command-card", "newt-command-card"],
] as const

// Component names are looked up by arbitrary route params (see
// apps/docs/src/pages/ComponentPage.tsx), so this stays a genuine open
// dictionary rather than a closed, literal-keyed type.
export const rootClasses: Record<string, string> =
  Object.fromEntries(rootClassEntries)
