// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import type { Registry } from "@/registry/schema"

export const examples: Registry = [
  {
    name: "action-row-demo",
    type: "registry:example",
    registryDependencies: ["action-row"],
    files: [
      {
        path: "examples/action-row-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "app-launcher-demo",
    type: "registry:example",
    registryDependencies: ["app-launcher"],
    files: [
      {
        path: "examples/app-launcher-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "attachment-demo",
    type: "registry:example",
    registryDependencies: ["attachment"],
    files: [
      {
        path: "examples/attachment-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "avatar-demo",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "examples/avatar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [
      {
        path: "examples/badge-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "bot-command-card-demo",
    type: "registry:example",
    registryDependencies: ["bot-command-card"],
    files: [
      {
        path: "examples/bot-command-card-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "examples/button-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "card-demo",
    type: "registry:example",
    registryDependencies: ["card"],
    files: [
      {
        path: "examples/card-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "channel-header-demo",
    type: "registry:example",
    registryDependencies: ["channel-header"],
    files: [
      {
        path: "examples/channel-header-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "channel-info-demo",
    type: "registry:example",
    registryDependencies: ["channel-info"],
    files: [
      {
        path: "examples/channel-info-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "channel-topic-demo",
    type: "registry:example",
    registryDependencies: ["channel-topic"],
    files: [
      {
        path: "examples/channel-topic-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "channel-welcome-demo",
    type: "registry:example",
    registryDependencies: ["channel-welcome"],
    files: [
      {
        path: "examples/channel-welcome-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "chat-demo",
    type: "registry:example",
    registryDependencies: ["chat"],
    files: [
      {
        path: "examples/chat-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "chat-window-demo",
    type: "registry:example",
    registryDependencies: ["chat-window"],
    files: [
      {
        path: "examples/chat-window-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "code-block-demo",
    type: "registry:example",
    registryDependencies: ["code-block"],
    files: [
      {
        path: "examples/code-block-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "command-panel-demo",
    type: "registry:example",
    registryDependencies: ["command-panel"],
    files: [
      {
        path: "examples/command-panel-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "context-menu-demo",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    files: [
      {
        path: "examples/context-menu-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "cooldown-bar-demo",
    type: "registry:example",
    registryDependencies: ["cooldown-bar"],
    files: [
      {
        path: "examples/cooldown-bar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "direction-demo",
    type: "registry:example",
    registryDependencies: ["direction"],
    files: [
      {
        path: "examples/direction-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "divider-demo",
    type: "registry:example",
    registryDependencies: ["divider"],
    files: [
      {
        path: "examples/divider-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "dropdown-demo",
    type: "registry:example",
    registryDependencies: ["dropdown"],
    files: [
      {
        path: "examples/dropdown-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "embed-demo",
    type: "registry:example",
    registryDependencies: ["embed"],
    files: [
      {
        path: "examples/embed-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "empty-state-demo",
    type: "registry:example",
    registryDependencies: ["empty-state"],
    files: [
      {
        path: "examples/empty-state-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "form-fields-demo",
    type: "registry:example",
    registryDependencies: ["form-fields"],
    files: [
      {
        path: "examples/form-fields-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "inline-code-demo",
    type: "registry:example",
    registryDependencies: ["inline-code"],
    files: [
      {
        path: "examples/inline-code-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "invite-demo",
    type: "registry:example",
    registryDependencies: ["invite"],
    files: [
      {
        path: "examples/invite-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "kbd-tag-demo",
    type: "registry:example",
    registryDependencies: ["kbd-tag"],
    files: [
      {
        path: "examples/kbd-tag-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "member-list-demo",
    type: "registry:example",
    registryDependencies: ["member-list"],
    files: [
      {
        path: "examples/member-list-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "mention-demo",
    type: "registry:example",
    registryDependencies: ["mention"],
    files: [
      {
        path: "examples/mention-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "message-composer-demo",
    type: "registry:example",
    registryDependencies: ["message-composer"],
    files: [
      {
        path: "examples/message-composer-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "message-group-demo",
    type: "registry:example",
    registryDependencies: ["message-group"],
    files: [
      {
        path: "examples/message-group-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "message-list-demo",
    type: "registry:example",
    registryDependencies: ["message-list"],
    files: [
      {
        path: "examples/message-list-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "modal-demo",
    type: "registry:example",
    registryDependencies: ["modal"],
    files: [
      {
        path: "examples/modal-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "notif-badge-demo",
    type: "registry:example",
    registryDependencies: ["notif-badge"],
    files: [
      {
        path: "examples/notif-badge-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "pagination-demo",
    type: "registry:example",
    registryDependencies: ["pagination"],
    files: [
      {
        path: "examples/pagination-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "permission-demo",
    type: "registry:example",
    registryDependencies: ["permission"],
    files: [
      {
        path: "examples/permission-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "progress-demo",
    type: "registry:example",
    registryDependencies: ["progress"],
    files: [
      {
        path: "examples/progress-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "radio-demo",
    type: "registry:example",
    registryDependencies: ["radio"],
    files: [
      {
        path: "examples/radio-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "reaction-demo",
    type: "registry:example",
    registryDependencies: ["reaction"],
    files: [
      {
        path: "examples/reaction-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "reply-preview-demo",
    type: "registry:example",
    registryDependencies: ["reply-preview"],
    files: [
      {
        path: "examples/reply-preview-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "role-tag-demo",
    type: "registry:example",
    registryDependencies: ["role-tag"],
    files: [
      {
        path: "examples/role-tag-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "scrollbar-demo",
    type: "registry:example",
    registryDependencies: ["scrollbar"],
    files: [
      {
        path: "examples/scrollbar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "select-menu-demo",
    type: "registry:example",
    registryDependencies: ["select-menu"],
    files: [
      {
        path: "examples/select-menu-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "server-banner-demo",
    type: "registry:example",
    registryDependencies: ["server-banner"],
    files: [
      {
        path: "examples/server-banner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "server-sidebar-demo",
    type: "registry:example",
    registryDependencies: ["server-sidebar"],
    files: [
      {
        path: "examples/server-sidebar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "skeleton-demo",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "examples/skeleton-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "slash-command-demo",
    type: "registry:example",
    registryDependencies: ["slash-command"],
    files: [
      {
        path: "examples/slash-command-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "slash-command-suggestions-demo",
    type: "registry:example",
    registryDependencies: ["slash-command-suggestions"],
    files: [
      {
        path: "examples/slash-command-suggestions-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "spoiler-demo",
    type: "registry:example",
    registryDependencies: ["spoiler"],
    files: [
      {
        path: "examples/spoiler-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "stage-banner-demo",
    type: "registry:example",
    registryDependencies: ["stage-banner"],
    files: [
      {
        path: "examples/stage-banner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "status-indicator-demo",
    type: "registry:example",
    registryDependencies: ["status-indicator"],
    files: [
      {
        path: "examples/status-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "tabs-demo",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [
      {
        path: "examples/tabs-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "timeline-demo",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: [
      {
        path: "examples/timeline-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "toast-demo",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: [
      {
        path: "examples/toast-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "token-field-demo",
    type: "registry:example",
    registryDependencies: ["token-field"],
    files: [
      {
        path: "examples/token-field-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "tooltip-demo",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    files: [
      {
        path: "examples/tooltip-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "typeset-demo",
    type: "registry:example",
    registryDependencies: ["typeset"],
    files: [
      {
        path: "examples/typeset-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "typing-indicator-demo",
    type: "registry:example",
    registryDependencies: ["typing-indicator"],
    files: [
      {
        path: "examples/typing-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "user-profile-demo",
    type: "registry:example",
    registryDependencies: ["user-profile"],
    files: [
      {
        path: "examples/user-profile-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "v2-container-demo",
    type: "registry:example",
    registryDependencies: ["v2-container"],
    files: [
      {
        path: "examples/v2-container-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "voice-channel-demo",
    type: "registry:example",
    registryDependencies: ["voice-channel"],
    files: [
      {
        path: "examples/voice-channel-demo.tsx",
        type: "registry:example",
      },
    ],
  },
]
