// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import { Registry } from "@/registry/schema"

export const examples: Registry = [
  {
    name: "action-row-demo",
    type: "registry:example",
    registryDependencies: ["action-row"],
    files: [
      {
        path: "example/action-row-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "attachment-demo",
    type: "registry:example",
    registryDependencies: ["attachment"],
    files: [
      {
        path: "example/attachment-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "avatar-demo",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "example/avatar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [
      {
        path: "example/badge-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "bot-command-card-demo",
    type: "registry:example",
    registryDependencies: ["bot-command-card"],
    files: [
      {
        path: "example/bot-command-card-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "example/button-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "card-demo",
    type: "registry:example",
    registryDependencies: ["card"],
    files: [
      {
        path: "example/card-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "channel-topic-demo",
    type: "registry:example",
    registryDependencies: ["channel-topic"],
    files: [
      {
        path: "example/channel-topic-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "chat-demo",
    type: "registry:example",
    registryDependencies: ["chat"],
    files: [
      {
        path: "example/chat-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "code-block-demo",
    type: "registry:example",
    registryDependencies: ["code-block"],
    files: [
      {
        path: "example/code-block-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "context-menu-demo",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    files: [
      {
        path: "example/context-menu-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "cooldown-bar-demo",
    type: "registry:example",
    registryDependencies: ["cooldown-bar"],
    files: [
      {
        path: "example/cooldown-bar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "divider-demo",
    type: "registry:example",
    registryDependencies: ["divider"],
    files: [
      {
        path: "example/divider-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "dropdown-demo",
    type: "registry:example",
    registryDependencies: ["dropdown"],
    files: [
      {
        path: "example/dropdown-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "embed-demo",
    type: "registry:example",
    registryDependencies: ["embed"],
    files: [
      {
        path: "example/embed-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "empty-state-demo",
    type: "registry:example",
    registryDependencies: ["empty-state"],
    files: [
      {
        path: "example/empty-state-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "form-fields-demo",
    type: "registry:example",
    registryDependencies: ["form-fields"],
    files: [
      {
        path: "example/form-fields-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "inline-code-demo",
    type: "registry:example",
    registryDependencies: ["inline-code"],
    files: [
      {
        path: "example/inline-code-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "kbd-tag-demo",
    type: "registry:example",
    registryDependencies: ["kbd-tag"],
    files: [
      {
        path: "example/kbd-tag-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "member-list-demo",
    type: "registry:example",
    registryDependencies: ["member-list"],
    files: [
      {
        path: "example/member-list-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "mention-demo",
    type: "registry:example",
    registryDependencies: ["mention"],
    files: [
      {
        path: "example/mention-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "message-composer-demo",
    type: "registry:example",
    registryDependencies: ["message-composer"],
    files: [
      {
        path: "example/message-composer-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "message-group-demo",
    type: "registry:example",
    registryDependencies: ["message-group"],
    files: [
      {
        path: "example/message-group-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "message-list-demo",
    type: "registry:example",
    registryDependencies: ["message-list"],
    files: [
      {
        path: "example/message-list-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "modal-demo",
    type: "registry:example",
    registryDependencies: ["modal"],
    files: [
      {
        path: "example/modal-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "notif-badge-demo",
    type: "registry:example",
    registryDependencies: ["notif-badge"],
    files: [
      {
        path: "example/notif-badge-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "pagination-demo",
    type: "registry:example",
    registryDependencies: ["pagination"],
    files: [
      {
        path: "example/pagination-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "permission-demo",
    type: "registry:example",
    registryDependencies: ["permission"],
    files: [
      {
        path: "example/permission-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "progress-demo",
    type: "registry:example",
    registryDependencies: ["progress"],
    files: [
      {
        path: "example/progress-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "reaction-demo",
    type: "registry:example",
    registryDependencies: ["reaction"],
    files: [
      {
        path: "example/reaction-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "reply-preview-demo",
    type: "registry:example",
    registryDependencies: ["reply-preview"],
    files: [
      {
        path: "example/reply-preview-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "role-tag-demo",
    type: "registry:example",
    registryDependencies: ["role-tag"],
    files: [
      {
        path: "example/role-tag-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "scrollbar-demo",
    type: "registry:example",
    registryDependencies: ["scrollbar"],
    files: [
      {
        path: "example/scrollbar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "select-menu-demo",
    type: "registry:example",
    registryDependencies: ["select-menu"],
    files: [
      {
        path: "example/select-menu-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "server-banner-demo",
    type: "registry:example",
    registryDependencies: ["server-banner"],
    files: [
      {
        path: "example/server-banner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "skeleton-demo",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "example/skeleton-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "slash-command-demo",
    type: "registry:example",
    registryDependencies: ["slash-command"],
    files: [
      {
        path: "example/slash-command-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "spoiler-demo",
    type: "registry:example",
    registryDependencies: ["spoiler"],
    files: [
      {
        path: "example/spoiler-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "stage-banner-demo",
    type: "registry:example",
    registryDependencies: ["stage-banner"],
    files: [
      {
        path: "example/stage-banner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "status-indicator-demo",
    type: "registry:example",
    registryDependencies: ["status-indicator"],
    files: [
      {
        path: "example/status-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "tabs-demo",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [
      {
        path: "example/tabs-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "timeline-demo",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: [
      {
        path: "example/timeline-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "toast-demo",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: [
      {
        path: "example/toast-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "token-field-demo",
    type: "registry:example",
    registryDependencies: ["token-field"],
    files: [
      {
        path: "example/token-field-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "tooltip-demo",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    files: [
      {
        path: "example/tooltip-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "typing-indicator-demo",
    type: "registry:example",
    registryDependencies: ["typing-indicator"],
    files: [
      {
        path: "example/typing-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "user-profile-demo",
    type: "registry:example",
    registryDependencies: ["user-profile"],
    files: [
      {
        path: "example/user-profile-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "voice-channel-demo",
    type: "registry:example",
    registryDependencies: ["voice-channel"],
    files: [
      {
        path: "example/voice-channel-demo.tsx",
        type: "registry:example",
      },
    ],
  },
]
