// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import type * as React from "react"

import ActionRowDemo from "@/registry/bases/newt/examples/action-row-demo"
import AppLauncherDemo from "@/registry/bases/newt/examples/app-launcher-demo"
import AttachmentDemo from "@/registry/bases/newt/examples/attachment-demo"
import AvatarDemo from "@/registry/bases/newt/examples/avatar-demo"
import BadgeDemo from "@/registry/bases/newt/examples/badge-demo"
import BotCommandCardDemo from "@/registry/bases/newt/examples/bot-command-card-demo"
import ButtonDemo from "@/registry/bases/newt/examples/button-demo"
import CardDemo from "@/registry/bases/newt/examples/card-demo"
import ChannelHeaderDemo from "@/registry/bases/newt/examples/channel-header-demo"
import ChannelInfoDemo from "@/registry/bases/newt/examples/channel-info-demo"
import ChannelTopicDemo from "@/registry/bases/newt/examples/channel-topic-demo"
import ChannelWelcomeDemo from "@/registry/bases/newt/examples/channel-welcome-demo"
import ChatDemo from "@/registry/bases/newt/examples/chat-demo"
import ChatWindowDemo from "@/registry/bases/newt/examples/chat-window-demo"
import CheckboxGroupDemo from "@/registry/bases/newt/examples/checkbox-group-demo"
import CodeBlockDemo from "@/registry/bases/newt/examples/code-block-demo"
import CommandPanelDemo from "@/registry/bases/newt/examples/command-panel-demo"
import ContextMenuDemo from "@/registry/bases/newt/examples/context-menu-demo"
import CooldownBarDemo from "@/registry/bases/newt/examples/cooldown-bar-demo"
import CustomEmojiDemo from "@/registry/bases/newt/examples/custom-emoji-demo"
import DirectionDemo from "@/registry/bases/newt/examples/direction-demo"
import DividerDemo from "@/registry/bases/newt/examples/divider-demo"
import DropdownDemo from "@/registry/bases/newt/examples/dropdown-demo"
import EmbedDemo from "@/registry/bases/newt/examples/embed-demo"
import EmptyStateDemo from "@/registry/bases/newt/examples/empty-state-demo"
import FileUploadDemo from "@/registry/bases/newt/examples/file-upload-demo"
import FormFieldsDemo from "@/registry/bases/newt/examples/form-fields-demo"
import InlineCodeDemo from "@/registry/bases/newt/examples/inline-code-demo"
import InviteDemo from "@/registry/bases/newt/examples/invite-demo"
import KbdTagDemo from "@/registry/bases/newt/examples/kbd-tag-demo"
import MediaGalleryDemo from "@/registry/bases/newt/examples/media-gallery-demo"
import MemberListDemo from "@/registry/bases/newt/examples/member-list-demo"
import MentionDemo from "@/registry/bases/newt/examples/mention-demo"
import MessageComposerDemo from "@/registry/bases/newt/examples/message-composer-demo"
import MessageGroupDemo from "@/registry/bases/newt/examples/message-group-demo"
import MessageListDemo from "@/registry/bases/newt/examples/message-list-demo"
import ModalDemo from "@/registry/bases/newt/examples/modal-demo"
import NotifBadgeDemo from "@/registry/bases/newt/examples/notif-badge-demo"
import PaginationDemo from "@/registry/bases/newt/examples/pagination-demo"
import PermissionDemo from "@/registry/bases/newt/examples/permission-demo"
import PollDemo from "@/registry/bases/newt/examples/poll-demo"
import ProgressDemo from "@/registry/bases/newt/examples/progress-demo"
import RadioDemo from "@/registry/bases/newt/examples/radio-demo"
import ReactionDemo from "@/registry/bases/newt/examples/reaction-demo"
import ReplyPreviewDemo from "@/registry/bases/newt/examples/reply-preview-demo"
import RoleTagDemo from "@/registry/bases/newt/examples/role-tag-demo"
import ScrollbarDemo from "@/registry/bases/newt/examples/scrollbar-demo"
import SectionDemo from "@/registry/bases/newt/examples/section-demo"
import SelectMenuDemo from "@/registry/bases/newt/examples/select-menu-demo"
import ServerBannerDemo from "@/registry/bases/newt/examples/server-banner-demo"
import ServerSidebarDemo from "@/registry/bases/newt/examples/server-sidebar-demo"
import SkeletonDemo from "@/registry/bases/newt/examples/skeleton-demo"
import SlashCommandDemo from "@/registry/bases/newt/examples/slash-command-demo"
import SlashCommandSuggestionsDemo from "@/registry/bases/newt/examples/slash-command-suggestions-demo"
import SpoilerDemo from "@/registry/bases/newt/examples/spoiler-demo"
import StageBannerDemo from "@/registry/bases/newt/examples/stage-banner-demo"
import StatusIndicatorDemo from "@/registry/bases/newt/examples/status-indicator-demo"
import SystemMessageDemo from "@/registry/bases/newt/examples/system-message-demo"
import TabsDemo from "@/registry/bases/newt/examples/tabs-demo"
import ThreadPreviewDemo from "@/registry/bases/newt/examples/thread-preview-demo"
import TimelineDemo from "@/registry/bases/newt/examples/timeline-demo"
import TimestampDemo from "@/registry/bases/newt/examples/timestamp-demo"
import ToastDemo from "@/registry/bases/newt/examples/toast-demo"
import TokenFieldDemo from "@/registry/bases/newt/examples/token-field-demo"
import TooltipDemo from "@/registry/bases/newt/examples/tooltip-demo"
import TypesetDemo from "@/registry/bases/newt/examples/typeset-demo"
import TypingIndicatorDemo from "@/registry/bases/newt/examples/typing-indicator-demo"
import UserProfileDemo from "@/registry/bases/newt/examples/user-profile-demo"
import V2ContainerDemo from "@/registry/bases/newt/examples/v2-container-demo"
import VoiceChannelDemo from "@/registry/bases/newt/examples/voice-channel-demo"

// Keys are the registry component names; built via `Object.fromEntries` (instead
// of a `Record<string, React.ComponentType>` literal) so the lookup map stays
// indexable by an arbitrary string without widening away the entry type.
const demoEntries: Array<[string, React.ComponentType]> = [
  ["action-row", ActionRowDemo],
  ["app-launcher", AppLauncherDemo],
  ["attachment", AttachmentDemo],
  ["avatar", AvatarDemo],
  ["badge", BadgeDemo],
  ["bot-command-card", BotCommandCardDemo],
  ["button", ButtonDemo],
  ["card", CardDemo],
  ["channel-header", ChannelHeaderDemo],
  ["channel-info", ChannelInfoDemo],
  ["channel-topic", ChannelTopicDemo],
  ["channel-welcome", ChannelWelcomeDemo],
  ["chat", ChatDemo],
  ["chat-window", ChatWindowDemo],
  ["checkbox-group", CheckboxGroupDemo],
  ["code-block", CodeBlockDemo],
  ["command-panel", CommandPanelDemo],
  ["context-menu", ContextMenuDemo],
  ["cooldown-bar", CooldownBarDemo],
  ["custom-emoji", CustomEmojiDemo],
  ["direction", DirectionDemo],
  ["divider", DividerDemo],
  ["dropdown", DropdownDemo],
  ["embed", EmbedDemo],
  ["empty-state", EmptyStateDemo],
  ["file-upload", FileUploadDemo],
  ["form-fields", FormFieldsDemo],
  ["inline-code", InlineCodeDemo],
  ["invite", InviteDemo],
  ["kbd-tag", KbdTagDemo],
  ["media-gallery", MediaGalleryDemo],
  ["member-list", MemberListDemo],
  ["mention", MentionDemo],
  ["message-composer", MessageComposerDemo],
  ["message-group", MessageGroupDemo],
  ["message-list", MessageListDemo],
  ["modal", ModalDemo],
  ["notif-badge", NotifBadgeDemo],
  ["pagination", PaginationDemo],
  ["permission", PermissionDemo],
  ["poll", PollDemo],
  ["progress", ProgressDemo],
  ["radio", RadioDemo],
  ["reaction", ReactionDemo],
  ["reply-preview", ReplyPreviewDemo],
  ["role-tag", RoleTagDemo],
  ["scrollbar", ScrollbarDemo],
  ["section", SectionDemo],
  ["select-menu", SelectMenuDemo],
  ["server-banner", ServerBannerDemo],
  ["server-sidebar", ServerSidebarDemo],
  ["skeleton", SkeletonDemo],
  ["slash-command", SlashCommandDemo],
  ["slash-command-suggestions", SlashCommandSuggestionsDemo],
  ["spoiler", SpoilerDemo],
  ["stage-banner", StageBannerDemo],
  ["status-indicator", StatusIndicatorDemo],
  ["system-message", SystemMessageDemo],
  ["tabs", TabsDemo],
  ["thread-preview", ThreadPreviewDemo],
  ["timeline", TimelineDemo],
  ["timestamp", TimestampDemo],
  ["toast", ToastDemo],
  ["token-field", TokenFieldDemo],
  ["tooltip", TooltipDemo],
  ["typeset", TypesetDemo],
  ["typing-indicator", TypingIndicatorDemo],
  ["user-profile", UserProfileDemo],
  ["v2-container", V2ContainerDemo],
  ["voice-channel", VoiceChannelDemo],
]

export const Demos = Object.fromEntries(demoEntries)
