// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import type * as React from "react"

import AttachmentDemo from "@/registry/default/example/attachment-demo"
import AvatarDemo from "@/registry/default/example/avatar-demo"
import BadgeDemo from "@/registry/default/example/badge-demo"
import BotCommandCardDemo from "@/registry/default/example/bot-command-card-demo"
import ButtonDemo from "@/registry/default/example/button-demo"
import CardDemo from "@/registry/default/example/card-demo"
import ChannelTopicDemo from "@/registry/default/example/channel-topic-demo"
import CodeBlockDemo from "@/registry/default/example/code-block-demo"
import ContextMenuDemo from "@/registry/default/example/context-menu-demo"
import CooldownBarDemo from "@/registry/default/example/cooldown-bar-demo"
import DividerDemo from "@/registry/default/example/divider-demo"
import DropdownDemo from "@/registry/default/example/dropdown-demo"
import EmbedDemo from "@/registry/default/example/embed-demo"
import EmptyStateDemo from "@/registry/default/example/empty-state-demo"
import FormFieldsDemo from "@/registry/default/example/form-fields-demo"
import KbdTagDemo from "@/registry/default/example/kbd-tag-demo"
import MemberListDemo from "@/registry/default/example/member-list-demo"
import MentionDemo from "@/registry/default/example/mention-demo"
import MessageGroupDemo from "@/registry/default/example/message-group-demo"
import ModalDemo from "@/registry/default/example/modal-demo"
import NotifBadgeDemo from "@/registry/default/example/notif-badge-demo"
import PaginationDemo from "@/registry/default/example/pagination-demo"
import PermissionDemo from "@/registry/default/example/permission-demo"
import ProgressDemo from "@/registry/default/example/progress-demo"
import ReactionDemo from "@/registry/default/example/reaction-demo"
import ReplyPreviewDemo from "@/registry/default/example/reply-preview-demo"
import RoleTagDemo from "@/registry/default/example/role-tag-demo"
import ScrollbarDemo from "@/registry/default/example/scrollbar-demo"
import SelectMenuDemo from "@/registry/default/example/select-menu-demo"
import ServerBannerDemo from "@/registry/default/example/server-banner-demo"
import SkeletonDemo from "@/registry/default/example/skeleton-demo"
import SlashCommandDemo from "@/registry/default/example/slash-command-demo"
import SpoilerDemo from "@/registry/default/example/spoiler-demo"
import StageBannerDemo from "@/registry/default/example/stage-banner-demo"
import StatusIndicatorDemo from "@/registry/default/example/status-indicator-demo"
import TabsDemo from "@/registry/default/example/tabs-demo"
import TimelineDemo from "@/registry/default/example/timeline-demo"
import ToastDemo from "@/registry/default/example/toast-demo"
import TokenFieldDemo from "@/registry/default/example/token-field-demo"
import TooltipDemo from "@/registry/default/example/tooltip-demo"
import TypingIndicatorDemo from "@/registry/default/example/typing-indicator-demo"
import UserProfileDemo from "@/registry/default/example/user-profile-demo"
import VoiceChannelDemo from "@/registry/default/example/voice-channel-demo"

// Keys are the registry component names; built via `Object.fromEntries` (instead
// of a `Record<string, React.ComponentType>` literal) so the lookup map stays
// indexable by an arbitrary string without widening away the entry type.
const demoEntries: Array<[string, React.ComponentType]> = [
  ["attachment", AttachmentDemo],
  ["avatar", AvatarDemo],
  ["badge", BadgeDemo],
  ["bot-command-card", BotCommandCardDemo],
  ["button", ButtonDemo],
  ["card", CardDemo],
  ["channel-topic", ChannelTopicDemo],
  ["code-block", CodeBlockDemo],
  ["context-menu", ContextMenuDemo],
  ["cooldown-bar", CooldownBarDemo],
  ["divider", DividerDemo],
  ["dropdown", DropdownDemo],
  ["embed", EmbedDemo],
  ["empty-state", EmptyStateDemo],
  ["form-fields", FormFieldsDemo],
  ["kbd-tag", KbdTagDemo],
  ["member-list", MemberListDemo],
  ["mention", MentionDemo],
  ["message-group", MessageGroupDemo],
  ["modal", ModalDemo],
  ["notif-badge", NotifBadgeDemo],
  ["pagination", PaginationDemo],
  ["permission", PermissionDemo],
  ["progress", ProgressDemo],
  ["reaction", ReactionDemo],
  ["reply-preview", ReplyPreviewDemo],
  ["role-tag", RoleTagDemo],
  ["scrollbar", ScrollbarDemo],
  ["select-menu", SelectMenuDemo],
  ["server-banner", ServerBannerDemo],
  ["skeleton", SkeletonDemo],
  ["slash-command", SlashCommandDemo],
  ["spoiler", SpoilerDemo],
  ["stage-banner", StageBannerDemo],
  ["status-indicator", StatusIndicatorDemo],
  ["tabs", TabsDemo],
  ["timeline", TimelineDemo],
  ["toast", ToastDemo],
  ["token-field", TokenFieldDemo],
  ["tooltip", TooltipDemo],
  ["typing-indicator", TypingIndicatorDemo],
  ["user-profile", UserProfileDemo],
  ["voice-channel", VoiceChannelDemo],
]

export const Demos = Object.fromEntries(demoEntries)
