// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
// @ts-nocheck
import * as React from "react"

interface RegistryIndexEntry {
  name: string
  type: string
  registryDependencies: string[]
  files: string[]
  component: React.ComponentType
}

// Keys are the registry component/example names; built via `Object.fromEntries`
// (instead of a `Record<string, any>` literal) so the lookup map stays
// indexable by an arbitrary string without widening away the entry type.
const registryIndexEntries: Array<[string, RegistryIndexEntry]> = [
  [
    "attachment",
    {
      name: "attachment",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/default/ui/attachment.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/attachment")),
    },
  ],
  [
    "avatar",
    {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/avatar.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/avatar")),
    },
  ],
  [
    "badge",
    {
      name: "badge",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/badge.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/badge")),
    },
  ],
  [
    "bot-command-card",
    {
      name: "bot-command-card",
      type: "registry:ui",
      registryDependencies: ["badge"],
      files: ["registry/default/ui/bot-command-card.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/bot-command-card")
      ),
    },
  ],
  [
    "button",
    {
      name: "button",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/button")),
    },
  ],
  [
    "card",
    {
      name: "card",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/card.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/card")),
    },
  ],
  [
    "channel-topic",
    {
      name: "channel-topic",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/channel-topic.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/channel-topic")
      ),
    },
  ],
  [
    "code-block",
    {
      name: "code-block",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/code-block.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/code-block")),
    },
  ],
  [
    "context-menu",
    {
      name: "context-menu",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/context-menu.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/context-menu")),
    },
  ],
  [
    "cooldown-bar",
    {
      name: "cooldown-bar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/cooldown-bar.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/cooldown-bar")),
    },
  ],
  [
    "divider",
    {
      name: "divider",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/divider.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/divider")),
    },
  ],
  [
    "dropdown",
    {
      name: "dropdown",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/dropdown.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/dropdown")),
    },
  ],
  [
    "embed",
    {
      name: "embed",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/embed.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/embed")),
    },
  ],
  [
    "empty-state",
    {
      name: "empty-state",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/empty-state.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/empty-state")),
    },
  ],
  [
    "form-fields",
    {
      name: "form-fields",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/form-fields.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/form-fields")),
    },
  ],
  [
    "kbd-tag",
    {
      name: "kbd-tag",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/kbd-tag.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/kbd-tag")),
    },
  ],
  [
    "member-list",
    {
      name: "member-list",
      type: "registry:ui",
      registryDependencies: ["avatar", "status-indicator", "role-tag"],
      files: ["registry/default/ui/member-list.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/member-list")),
    },
  ],
  [
    "mention",
    {
      name: "mention",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/mention.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/mention")),
    },
  ],
  [
    "message-group",
    {
      name: "message-group",
      type: "registry:ui",
      registryDependencies: ["avatar", "status-indicator", "reaction"],
      files: ["registry/default/ui/message-group.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/message-group")
      ),
    },
  ],
  [
    "modal",
    {
      name: "modal",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/default/ui/modal.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/modal")),
    },
  ],
  [
    "notif-badge",
    {
      name: "notif-badge",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: ["registry/default/ui/notif-badge.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/notif-badge")),
    },
  ],
  [
    "pagination",
    {
      name: "pagination",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/default/ui/pagination.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/pagination")),
    },
  ],
  [
    "permission",
    {
      name: "permission",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/permission.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/permission")),
    },
  ],
  [
    "progress",
    {
      name: "progress",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/progress.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/progress")),
    },
  ],
  [
    "reaction",
    {
      name: "reaction",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/reaction.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/reaction")),
    },
  ],
  [
    "reply-preview",
    {
      name: "reply-preview",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/reply-preview.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/reply-preview")
      ),
    },
  ],
  [
    "role-tag",
    {
      name: "role-tag",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/role-tag.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/role-tag")),
    },
  ],
  [
    "scrollbar",
    {
      name: "scrollbar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/scrollbar.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/scrollbar")),
    },
  ],
  [
    "select-menu",
    {
      name: "select-menu",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/select-menu.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/select-menu")),
    },
  ],
  [
    "server-banner",
    {
      name: "server-banner",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/default/ui/server-banner.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/server-banner")
      ),
    },
  ],
  [
    "skeleton",
    {
      name: "skeleton",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/skeleton.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/skeleton")),
    },
  ],
  [
    "slash-command",
    {
      name: "slash-command",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/slash-command.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/slash-command")
      ),
    },
  ],
  [
    "spoiler",
    {
      name: "spoiler",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/spoiler.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/spoiler")),
    },
  ],
  [
    "stage-banner",
    {
      name: "stage-banner",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/stage-banner.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/stage-banner")),
    },
  ],
  [
    "status-indicator",
    {
      name: "status-indicator",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: ["registry/default/ui/status-indicator.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/status-indicator")
      ),
    },
  ],
  [
    "tabs",
    {
      name: "tabs",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/tabs.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/tabs")),
    },
  ],
  [
    "timeline",
    {
      name: "timeline",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/timeline.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/timeline")),
    },
  ],
  [
    "toast",
    {
      name: "toast",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/toast.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/toast")),
    },
  ],
  [
    "token-field",
    {
      name: "token-field",
      type: "registry:ui",
      registryDependencies: ["form-fields", "button"],
      files: ["registry/default/ui/token-field.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/token-field")),
    },
  ],
  [
    "tooltip",
    {
      name: "tooltip",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/tooltip.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/tooltip")),
    },
  ],
  [
    "typing-indicator",
    {
      name: "typing-indicator",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/default/ui/typing-indicator.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/typing-indicator")
      ),
    },
  ],
  [
    "user-profile",
    {
      name: "user-profile",
      type: "registry:ui",
      registryDependencies: [
        "avatar",
        "status-indicator",
        "role-tag",
        "button",
      ],
      files: ["registry/default/ui/user-profile.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/user-profile")),
    },
  ],
  [
    "voice-channel",
    {
      name: "voice-channel",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: ["registry/default/ui/voice-channel.tsx"],
      component: React.lazy(
        () => import("@/registry/default/ui/voice-channel")
      ),
    },
  ],
  [
    "attachment-demo",
    {
      name: "attachment-demo",
      type: "registry:example",
      registryDependencies: ["attachment"],
      files: ["registry/default/example/attachment-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/attachment-demo")
      ),
    },
  ],
  [
    "avatar-demo",
    {
      name: "avatar-demo",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: ["registry/default/example/avatar-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/avatar-demo")
      ),
    },
  ],
  [
    "badge-demo",
    {
      name: "badge-demo",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: ["registry/default/example/badge-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/badge-demo")
      ),
    },
  ],
  [
    "bot-command-card-demo",
    {
      name: "bot-command-card-demo",
      type: "registry:example",
      registryDependencies: ["bot-command-card"],
      files: ["registry/default/example/bot-command-card-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/bot-command-card-demo")
      ),
    },
  ],
  [
    "button-demo",
    {
      name: "button-demo",
      type: "registry:example",
      registryDependencies: ["button"],
      files: ["registry/default/example/button-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/button-demo")
      ),
    },
  ],
  [
    "card-demo",
    {
      name: "card-demo",
      type: "registry:example",
      registryDependencies: ["card"],
      files: ["registry/default/example/card-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/card-demo")
      ),
    },
  ],
  [
    "channel-topic-demo",
    {
      name: "channel-topic-demo",
      type: "registry:example",
      registryDependencies: ["channel-topic"],
      files: ["registry/default/example/channel-topic-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/channel-topic-demo")
      ),
    },
  ],
  [
    "code-block-demo",
    {
      name: "code-block-demo",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: ["registry/default/example/code-block-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/code-block-demo")
      ),
    },
  ],
  [
    "context-menu-demo",
    {
      name: "context-menu-demo",
      type: "registry:example",
      registryDependencies: ["context-menu"],
      files: ["registry/default/example/context-menu-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/context-menu-demo")
      ),
    },
  ],
  [
    "cooldown-bar-demo",
    {
      name: "cooldown-bar-demo",
      type: "registry:example",
      registryDependencies: ["cooldown-bar"],
      files: ["registry/default/example/cooldown-bar-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/cooldown-bar-demo")
      ),
    },
  ],
  [
    "divider-demo",
    {
      name: "divider-demo",
      type: "registry:example",
      registryDependencies: ["divider"],
      files: ["registry/default/example/divider-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/divider-demo")
      ),
    },
  ],
  [
    "dropdown-demo",
    {
      name: "dropdown-demo",
      type: "registry:example",
      registryDependencies: ["dropdown"],
      files: ["registry/default/example/dropdown-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/dropdown-demo")
      ),
    },
  ],
  [
    "embed-demo",
    {
      name: "embed-demo",
      type: "registry:example",
      registryDependencies: ["embed"],
      files: ["registry/default/example/embed-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/embed-demo")
      ),
    },
  ],
  [
    "empty-state-demo",
    {
      name: "empty-state-demo",
      type: "registry:example",
      registryDependencies: ["empty-state"],
      files: ["registry/default/example/empty-state-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/empty-state-demo")
      ),
    },
  ],
  [
    "form-fields-demo",
    {
      name: "form-fields-demo",
      type: "registry:example",
      registryDependencies: ["form-fields"],
      files: ["registry/default/example/form-fields-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/form-fields-demo")
      ),
    },
  ],
  [
    "kbd-tag-demo",
    {
      name: "kbd-tag-demo",
      type: "registry:example",
      registryDependencies: ["kbd-tag"],
      files: ["registry/default/example/kbd-tag-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/kbd-tag-demo")
      ),
    },
  ],
  [
    "member-list-demo",
    {
      name: "member-list-demo",
      type: "registry:example",
      registryDependencies: ["member-list"],
      files: ["registry/default/example/member-list-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/member-list-demo")
      ),
    },
  ],
  [
    "mention-demo",
    {
      name: "mention-demo",
      type: "registry:example",
      registryDependencies: ["mention"],
      files: ["registry/default/example/mention-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/mention-demo")
      ),
    },
  ],
  [
    "message-group-demo",
    {
      name: "message-group-demo",
      type: "registry:example",
      registryDependencies: ["message-group"],
      files: ["registry/default/example/message-group-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/message-group-demo")
      ),
    },
  ],
  [
    "modal-demo",
    {
      name: "modal-demo",
      type: "registry:example",
      registryDependencies: ["modal"],
      files: ["registry/default/example/modal-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/modal-demo")
      ),
    },
  ],
  [
    "notif-badge-demo",
    {
      name: "notif-badge-demo",
      type: "registry:example",
      registryDependencies: ["notif-badge"],
      files: ["registry/default/example/notif-badge-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/notif-badge-demo")
      ),
    },
  ],
  [
    "pagination-demo",
    {
      name: "pagination-demo",
      type: "registry:example",
      registryDependencies: ["pagination"],
      files: ["registry/default/example/pagination-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/pagination-demo")
      ),
    },
  ],
  [
    "permission-demo",
    {
      name: "permission-demo",
      type: "registry:example",
      registryDependencies: ["permission"],
      files: ["registry/default/example/permission-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/permission-demo")
      ),
    },
  ],
  [
    "progress-demo",
    {
      name: "progress-demo",
      type: "registry:example",
      registryDependencies: ["progress"],
      files: ["registry/default/example/progress-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/progress-demo")
      ),
    },
  ],
  [
    "reaction-demo",
    {
      name: "reaction-demo",
      type: "registry:example",
      registryDependencies: ["reaction"],
      files: ["registry/default/example/reaction-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/reaction-demo")
      ),
    },
  ],
  [
    "reply-preview-demo",
    {
      name: "reply-preview-demo",
      type: "registry:example",
      registryDependencies: ["reply-preview"],
      files: ["registry/default/example/reply-preview-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/reply-preview-demo")
      ),
    },
  ],
  [
    "role-tag-demo",
    {
      name: "role-tag-demo",
      type: "registry:example",
      registryDependencies: ["role-tag"],
      files: ["registry/default/example/role-tag-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/role-tag-demo")
      ),
    },
  ],
  [
    "scrollbar-demo",
    {
      name: "scrollbar-demo",
      type: "registry:example",
      registryDependencies: ["scrollbar"],
      files: ["registry/default/example/scrollbar-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/scrollbar-demo")
      ),
    },
  ],
  [
    "select-menu-demo",
    {
      name: "select-menu-demo",
      type: "registry:example",
      registryDependencies: ["select-menu"],
      files: ["registry/default/example/select-menu-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/select-menu-demo")
      ),
    },
  ],
  [
    "server-banner-demo",
    {
      name: "server-banner-demo",
      type: "registry:example",
      registryDependencies: ["server-banner"],
      files: ["registry/default/example/server-banner-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/server-banner-demo")
      ),
    },
  ],
  [
    "skeleton-demo",
    {
      name: "skeleton-demo",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: ["registry/default/example/skeleton-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/skeleton-demo")
      ),
    },
  ],
  [
    "slash-command-demo",
    {
      name: "slash-command-demo",
      type: "registry:example",
      registryDependencies: ["slash-command"],
      files: ["registry/default/example/slash-command-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/slash-command-demo")
      ),
    },
  ],
  [
    "spoiler-demo",
    {
      name: "spoiler-demo",
      type: "registry:example",
      registryDependencies: ["spoiler"],
      files: ["registry/default/example/spoiler-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/spoiler-demo")
      ),
    },
  ],
  [
    "stage-banner-demo",
    {
      name: "stage-banner-demo",
      type: "registry:example",
      registryDependencies: ["stage-banner"],
      files: ["registry/default/example/stage-banner-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/stage-banner-demo")
      ),
    },
  ],
  [
    "status-indicator-demo",
    {
      name: "status-indicator-demo",
      type: "registry:example",
      registryDependencies: ["status-indicator"],
      files: ["registry/default/example/status-indicator-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/status-indicator-demo")
      ),
    },
  ],
  [
    "tabs-demo",
    {
      name: "tabs-demo",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: ["registry/default/example/tabs-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/tabs-demo")
      ),
    },
  ],
  [
    "timeline-demo",
    {
      name: "timeline-demo",
      type: "registry:example",
      registryDependencies: ["timeline"],
      files: ["registry/default/example/timeline-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/timeline-demo")
      ),
    },
  ],
  [
    "toast-demo",
    {
      name: "toast-demo",
      type: "registry:example",
      registryDependencies: ["toast"],
      files: ["registry/default/example/toast-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/toast-demo")
      ),
    },
  ],
  [
    "token-field-demo",
    {
      name: "token-field-demo",
      type: "registry:example",
      registryDependencies: ["token-field"],
      files: ["registry/default/example/token-field-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/token-field-demo")
      ),
    },
  ],
  [
    "tooltip-demo",
    {
      name: "tooltip-demo",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: ["registry/default/example/tooltip-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/tooltip-demo")
      ),
    },
  ],
  [
    "typing-indicator-demo",
    {
      name: "typing-indicator-demo",
      type: "registry:example",
      registryDependencies: ["typing-indicator"],
      files: ["registry/default/example/typing-indicator-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/typing-indicator-demo")
      ),
    },
  ],
  [
    "user-profile-demo",
    {
      name: "user-profile-demo",
      type: "registry:example",
      registryDependencies: ["user-profile"],
      files: ["registry/default/example/user-profile-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/user-profile-demo")
      ),
    },
  ],
  [
    "voice-channel-demo",
    {
      name: "voice-channel-demo",
      type: "registry:example",
      registryDependencies: ["voice-channel"],
      files: ["registry/default/example/voice-channel-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/default/example/voice-channel-demo")
      ),
    },
  ],
]

export const Index = {
  default: Object.fromEntries(registryIndexEntries),
}
