// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
// @ts-nocheck
import * as React from "react"

interface RegistryIndexEntry {
  name: string
  type: string
  registryDependencies: string[]
  files: string[]
  component: React.ComponentType
}

// Keys are the registry component/example names; built via `Object.fromEntries`
// (instead of a `Record<string, any>` literal) so the lookup map stays
// indexable by an arbitrary string without widening away the entry type.
const registryIndexEntries: Array<[string, RegistryIndexEntry]> = [
  [
    "action-row",
    {
      name: "action-row",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/ui/action-row.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/action-row")
      ),
    },
  ],
  [
    "app-launcher",
    {
      name: "app-launcher",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/app-launcher.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/app-launcher")
      ),
    },
  ],
  [
    "attachment",
    {
      name: "attachment",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/ui/attachment.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/attachment")
      ),
    },
  ],
  [
    "avatar",
    {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/avatar.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/avatar")),
    },
  ],
  [
    "badge",
    {
      name: "badge",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/badge.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/badge")),
    },
  ],
  [
    "bot-command-card",
    {
      name: "bot-command-card",
      type: "registry:ui",
      registryDependencies: ["badge"],
      files: ["registry/bases/newt/ui/bot-command-card.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/bot-command-card")
      ),
    },
  ],
  [
    "button",
    {
      name: "button",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/button")),
    },
  ],
  [
    "card",
    {
      name: "card",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/card.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/card")),
    },
  ],
  [
    "channel-header",
    {
      name: "channel-header",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/channel-header.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/channel-header")
      ),
    },
  ],
  [
    "channel-info",
    {
      name: "channel-info",
      type: "registry:ui",
      registryDependencies: ["tabs"],
      files: ["registry/bases/newt/ui/channel-info.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/channel-info")
      ),
    },
  ],
  [
    "channel-topic",
    {
      name: "channel-topic",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/channel-topic.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/channel-topic")
      ),
    },
  ],
  [
    "channel-welcome",
    {
      name: "channel-welcome",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/channel-welcome.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/channel-welcome")
      ),
    },
  ],
  [
    "chat",
    {
      name: "chat",
      type: "registry:ui",
      registryDependencies: ["scrollbar", "message-list", "message-composer"],
      files: ["registry/bases/newt/ui/chat.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/chat")),
    },
  ],
  [
    "chat-window",
    {
      name: "chat-window",
      type: "registry:block",
      registryDependencies: [
        "channel-header",
        "chat",
        "message-list",
        "message-group",
        "message-composer",
        "avatar",
      ],
      files: ["registry/bases/newt/blocks/chat-window/chat-window.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/blocks/chat-window/chat-window")
      ),
    },
  ],
  [
    "code-block",
    {
      name: "code-block",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/code-block.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/code-block")
      ),
    },
  ],
  [
    "command-panel",
    {
      name: "command-panel",
      type: "registry:block",
      registryDependencies: ["slash-command-suggestions", "bot-command-card"],
      files: ["registry/bases/newt/blocks/command-panel/command-panel.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/blocks/command-panel/command-panel")
      ),
    },
  ],
  [
    "context-menu",
    {
      name: "context-menu",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/context-menu.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/context-menu")
      ),
    },
  ],
  [
    "cooldown-bar",
    {
      name: "cooldown-bar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/cooldown-bar.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/cooldown-bar")
      ),
    },
  ],
  [
    "direction",
    {
      name: "direction",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/direction.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/direction")),
    },
  ],
  [
    "divider",
    {
      name: "divider",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/divider.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/divider")),
    },
  ],
  [
    "dropdown",
    {
      name: "dropdown",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/dropdown.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/dropdown")),
    },
  ],
  [
    "embed",
    {
      name: "embed",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/embed.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/embed")),
    },
  ],
  [
    "empty-state",
    {
      name: "empty-state",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/empty-state.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/empty-state")
      ),
    },
  ],
  [
    "form-fields",
    {
      name: "form-fields",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/form-fields.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/form-fields")
      ),
    },
  ],
  [
    "inline-code",
    {
      name: "inline-code",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/inline-code.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/inline-code")
      ),
    },
  ],
  [
    "invite",
    {
      name: "invite",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/ui/invite.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/invite")),
    },
  ],
  [
    "kbd-tag",
    {
      name: "kbd-tag",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/kbd-tag.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/kbd-tag")),
    },
  ],
  [
    "member-list",
    {
      name: "member-list",
      type: "registry:ui",
      registryDependencies: ["avatar", "status-indicator", "role-tag"],
      files: ["registry/bases/newt/ui/member-list.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/member-list")
      ),
    },
  ],
  [
    "mention",
    {
      name: "mention",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/mention.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/mention")),
    },
  ],
  [
    "message-composer",
    {
      name: "message-composer",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/message-composer.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/message-composer")
      ),
    },
  ],
  [
    "message-group",
    {
      name: "message-group",
      type: "registry:ui",
      registryDependencies: [
        "avatar",
        "reaction",
        "reply-preview",
        "status-indicator",
      ],
      files: ["registry/bases/newt/ui/message-group.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/message-group")
      ),
    },
  ],
  [
    "message-list",
    {
      name: "message-list",
      type: "registry:ui",
      registryDependencies: ["message-group"],
      files: ["registry/bases/newt/ui/message-list.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/message-list")
      ),
    },
  ],
  [
    "modal",
    {
      name: "modal",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/ui/modal.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/modal")),
    },
  ],
  [
    "notif-badge",
    {
      name: "notif-badge",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: ["registry/bases/newt/ui/notif-badge.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/notif-badge")
      ),
    },
  ],
  [
    "pagination",
    {
      name: "pagination",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/ui/pagination.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/pagination")
      ),
    },
  ],
  [
    "permission",
    {
      name: "permission",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/permission.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/permission")
      ),
    },
  ],
  [
    "progress",
    {
      name: "progress",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/progress.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/progress")),
    },
  ],
  [
    "radio",
    {
      name: "radio",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/radio.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/radio")),
    },
  ],
  [
    "reaction",
    {
      name: "reaction",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/reaction.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/reaction")),
    },
  ],
  [
    "reply-preview",
    {
      name: "reply-preview",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/reply-preview.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/reply-preview")
      ),
    },
  ],
  [
    "role-tag",
    {
      name: "role-tag",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/role-tag.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/role-tag")),
    },
  ],
  [
    "scrollbar",
    {
      name: "scrollbar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/scrollbar.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/scrollbar")),
    },
  ],
  [
    "select-menu",
    {
      name: "select-menu",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/select-menu.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/select-menu")
      ),
    },
  ],
  [
    "server-banner",
    {
      name: "server-banner",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/ui/server-banner.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/server-banner")
      ),
    },
  ],
  [
    "server-sidebar",
    {
      name: "server-sidebar",
      type: "registry:block",
      registryDependencies: [
        "server-banner",
        "voice-channel",
        "member-list",
        "status-indicator",
        "avatar",
      ],
      files: ["registry/bases/newt/blocks/server-sidebar/server-sidebar.tsx"],
      component: React.lazy(
        () =>
          import("@/registry/bases/newt/blocks/server-sidebar/server-sidebar")
      ),
    },
  ],
  [
    "skeleton",
    {
      name: "skeleton",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/skeleton.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/skeleton")),
    },
  ],
  [
    "slash-command",
    {
      name: "slash-command",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/slash-command.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/slash-command")
      ),
    },
  ],
  [
    "slash-command-suggestions",
    {
      name: "slash-command-suggestions",
      type: "registry:ui",
      registryDependencies: ["slash-command"],
      files: ["registry/bases/newt/ui/slash-command-suggestions.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/slash-command-suggestions")
      ),
    },
  ],
  [
    "spoiler",
    {
      name: "spoiler",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/spoiler.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/spoiler")),
    },
  ],
  [
    "stage-banner",
    {
      name: "stage-banner",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/stage-banner.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/stage-banner")
      ),
    },
  ],
  [
    "status-indicator",
    {
      name: "status-indicator",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: ["registry/bases/newt/ui/status-indicator.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/status-indicator")
      ),
    },
  ],
  [
    "tabs",
    {
      name: "tabs",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/tabs.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/tabs")),
    },
  ],
  [
    "timeline",
    {
      name: "timeline",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/timeline.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/timeline")),
    },
  ],
  [
    "toast",
    {
      name: "toast",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/toast.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/toast")),
    },
  ],
  [
    "token-field",
    {
      name: "token-field",
      type: "registry:ui",
      registryDependencies: ["form-fields", "button"],
      files: ["registry/bases/newt/ui/token-field.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/token-field")
      ),
    },
  ],
  [
    "tooltip",
    {
      name: "tooltip",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/tooltip.tsx"],
      component: React.lazy(() => import("@/registry/bases/newt/ui/tooltip")),
    },
  ],
  [
    "typing-indicator",
    {
      name: "typing-indicator",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/typing-indicator.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/typing-indicator")
      ),
    },
  ],
  [
    "user-profile",
    {
      name: "user-profile",
      type: "registry:ui",
      registryDependencies: [
        "avatar",
        "status-indicator",
        "role-tag",
        "button",
      ],
      files: ["registry/bases/newt/ui/user-profile.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/user-profile")
      ),
    },
  ],
  [
    "v2-container",
    {
      name: "v2-container",
      type: "registry:ui",
      registryDependencies: [],
      files: ["registry/bases/newt/ui/v2-container.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/v2-container")
      ),
    },
  ],
  [
    "voice-channel",
    {
      name: "voice-channel",
      type: "registry:ui",
      registryDependencies: ["avatar"],
      files: ["registry/bases/newt/ui/voice-channel.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/ui/voice-channel")
      ),
    },
  ],
  [
    "action-row-demo",
    {
      name: "action-row-demo",
      type: "registry:example",
      registryDependencies: ["action-row"],
      files: ["registry/bases/newt/examples/action-row-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/action-row-demo")
      ),
    },
  ],
  [
    "app-launcher-demo",
    {
      name: "app-launcher-demo",
      type: "registry:example",
      registryDependencies: ["app-launcher"],
      files: ["registry/bases/newt/examples/app-launcher-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/app-launcher-demo")
      ),
    },
  ],
  [
    "attachment-demo",
    {
      name: "attachment-demo",
      type: "registry:example",
      registryDependencies: ["attachment"],
      files: ["registry/bases/newt/examples/attachment-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/attachment-demo")
      ),
    },
  ],
  [
    "avatar-demo",
    {
      name: "avatar-demo",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: ["registry/bases/newt/examples/avatar-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/avatar-demo")
      ),
    },
  ],
  [
    "badge-demo",
    {
      name: "badge-demo",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: ["registry/bases/newt/examples/badge-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/badge-demo")
      ),
    },
  ],
  [
    "bot-command-card-demo",
    {
      name: "bot-command-card-demo",
      type: "registry:example",
      registryDependencies: ["bot-command-card"],
      files: ["registry/bases/newt/examples/bot-command-card-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/bot-command-card-demo")
      ),
    },
  ],
  [
    "button-demo",
    {
      name: "button-demo",
      type: "registry:example",
      registryDependencies: ["button"],
      files: ["registry/bases/newt/examples/button-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/button-demo")
      ),
    },
  ],
  [
    "card-demo",
    {
      name: "card-demo",
      type: "registry:example",
      registryDependencies: ["card"],
      files: ["registry/bases/newt/examples/card-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/card-demo")
      ),
    },
  ],
  [
    "channel-header-demo",
    {
      name: "channel-header-demo",
      type: "registry:example",
      registryDependencies: ["channel-header"],
      files: ["registry/bases/newt/examples/channel-header-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/channel-header-demo")
      ),
    },
  ],
  [
    "channel-info-demo",
    {
      name: "channel-info-demo",
      type: "registry:example",
      registryDependencies: ["channel-info"],
      files: ["registry/bases/newt/examples/channel-info-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/channel-info-demo")
      ),
    },
  ],
  [
    "channel-topic-demo",
    {
      name: "channel-topic-demo",
      type: "registry:example",
      registryDependencies: ["channel-topic"],
      files: ["registry/bases/newt/examples/channel-topic-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/channel-topic-demo")
      ),
    },
  ],
  [
    "channel-welcome-demo",
    {
      name: "channel-welcome-demo",
      type: "registry:example",
      registryDependencies: ["channel-welcome"],
      files: ["registry/bases/newt/examples/channel-welcome-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/channel-welcome-demo")
      ),
    },
  ],
  [
    "chat-demo",
    {
      name: "chat-demo",
      type: "registry:example",
      registryDependencies: ["chat"],
      files: ["registry/bases/newt/examples/chat-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/chat-demo")
      ),
    },
  ],
  [
    "chat-window-demo",
    {
      name: "chat-window-demo",
      type: "registry:example",
      registryDependencies: ["chat-window"],
      files: ["registry/bases/newt/examples/chat-window-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/chat-window-demo")
      ),
    },
  ],
  [
    "code-block-demo",
    {
      name: "code-block-demo",
      type: "registry:example",
      registryDependencies: ["code-block"],
      files: ["registry/bases/newt/examples/code-block-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/code-block-demo")
      ),
    },
  ],
  [
    "command-panel-demo",
    {
      name: "command-panel-demo",
      type: "registry:example",
      registryDependencies: ["command-panel"],
      files: ["registry/bases/newt/examples/command-panel-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/command-panel-demo")
      ),
    },
  ],
  [
    "context-menu-demo",
    {
      name: "context-menu-demo",
      type: "registry:example",
      registryDependencies: ["context-menu"],
      files: ["registry/bases/newt/examples/context-menu-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/context-menu-demo")
      ),
    },
  ],
  [
    "cooldown-bar-demo",
    {
      name: "cooldown-bar-demo",
      type: "registry:example",
      registryDependencies: ["cooldown-bar"],
      files: ["registry/bases/newt/examples/cooldown-bar-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/cooldown-bar-demo")
      ),
    },
  ],
  [
    "direction-demo",
    {
      name: "direction-demo",
      type: "registry:example",
      registryDependencies: ["direction"],
      files: ["registry/bases/newt/examples/direction-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/direction-demo")
      ),
    },
  ],
  [
    "divider-demo",
    {
      name: "divider-demo",
      type: "registry:example",
      registryDependencies: ["divider"],
      files: ["registry/bases/newt/examples/divider-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/divider-demo")
      ),
    },
  ],
  [
    "dropdown-demo",
    {
      name: "dropdown-demo",
      type: "registry:example",
      registryDependencies: ["dropdown"],
      files: ["registry/bases/newt/examples/dropdown-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/dropdown-demo")
      ),
    },
  ],
  [
    "embed-demo",
    {
      name: "embed-demo",
      type: "registry:example",
      registryDependencies: ["embed"],
      files: ["registry/bases/newt/examples/embed-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/embed-demo")
      ),
    },
  ],
  [
    "empty-state-demo",
    {
      name: "empty-state-demo",
      type: "registry:example",
      registryDependencies: ["empty-state"],
      files: ["registry/bases/newt/examples/empty-state-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/empty-state-demo")
      ),
    },
  ],
  [
    "form-fields-demo",
    {
      name: "form-fields-demo",
      type: "registry:example",
      registryDependencies: ["form-fields"],
      files: ["registry/bases/newt/examples/form-fields-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/form-fields-demo")
      ),
    },
  ],
  [
    "inline-code-demo",
    {
      name: "inline-code-demo",
      type: "registry:example",
      registryDependencies: ["inline-code"],
      files: ["registry/bases/newt/examples/inline-code-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/inline-code-demo")
      ),
    },
  ],
  [
    "invite-demo",
    {
      name: "invite-demo",
      type: "registry:example",
      registryDependencies: ["invite"],
      files: ["registry/bases/newt/examples/invite-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/invite-demo")
      ),
    },
  ],
  [
    "kbd-tag-demo",
    {
      name: "kbd-tag-demo",
      type: "registry:example",
      registryDependencies: ["kbd-tag"],
      files: ["registry/bases/newt/examples/kbd-tag-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/kbd-tag-demo")
      ),
    },
  ],
  [
    "member-list-demo",
    {
      name: "member-list-demo",
      type: "registry:example",
      registryDependencies: ["member-list"],
      files: ["registry/bases/newt/examples/member-list-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/member-list-demo")
      ),
    },
  ],
  [
    "mention-demo",
    {
      name: "mention-demo",
      type: "registry:example",
      registryDependencies: ["mention"],
      files: ["registry/bases/newt/examples/mention-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/mention-demo")
      ),
    },
  ],
  [
    "message-composer-demo",
    {
      name: "message-composer-demo",
      type: "registry:example",
      registryDependencies: ["message-composer"],
      files: ["registry/bases/newt/examples/message-composer-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/message-composer-demo")
      ),
    },
  ],
  [
    "message-group-demo",
    {
      name: "message-group-demo",
      type: "registry:example",
      registryDependencies: ["message-group"],
      files: ["registry/bases/newt/examples/message-group-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/message-group-demo")
      ),
    },
  ],
  [
    "message-list-demo",
    {
      name: "message-list-demo",
      type: "registry:example",
      registryDependencies: ["message-list"],
      files: ["registry/bases/newt/examples/message-list-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/message-list-demo")
      ),
    },
  ],
  [
    "modal-demo",
    {
      name: "modal-demo",
      type: "registry:example",
      registryDependencies: ["modal"],
      files: ["registry/bases/newt/examples/modal-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/modal-demo")
      ),
    },
  ],
  [
    "notif-badge-demo",
    {
      name: "notif-badge-demo",
      type: "registry:example",
      registryDependencies: ["notif-badge"],
      files: ["registry/bases/newt/examples/notif-badge-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/notif-badge-demo")
      ),
    },
  ],
  [
    "pagination-demo",
    {
      name: "pagination-demo",
      type: "registry:example",
      registryDependencies: ["pagination"],
      files: ["registry/bases/newt/examples/pagination-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/pagination-demo")
      ),
    },
  ],
  [
    "permission-demo",
    {
      name: "permission-demo",
      type: "registry:example",
      registryDependencies: ["permission"],
      files: ["registry/bases/newt/examples/permission-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/permission-demo")
      ),
    },
  ],
  [
    "progress-demo",
    {
      name: "progress-demo",
      type: "registry:example",
      registryDependencies: ["progress"],
      files: ["registry/bases/newt/examples/progress-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/progress-demo")
      ),
    },
  ],
  [
    "radio-demo",
    {
      name: "radio-demo",
      type: "registry:example",
      registryDependencies: ["radio"],
      files: ["registry/bases/newt/examples/radio-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/radio-demo")
      ),
    },
  ],
  [
    "reaction-demo",
    {
      name: "reaction-demo",
      type: "registry:example",
      registryDependencies: ["reaction"],
      files: ["registry/bases/newt/examples/reaction-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/reaction-demo")
      ),
    },
  ],
  [
    "reply-preview-demo",
    {
      name: "reply-preview-demo",
      type: "registry:example",
      registryDependencies: ["reply-preview"],
      files: ["registry/bases/newt/examples/reply-preview-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/reply-preview-demo")
      ),
    },
  ],
  [
    "role-tag-demo",
    {
      name: "role-tag-demo",
      type: "registry:example",
      registryDependencies: ["role-tag"],
      files: ["registry/bases/newt/examples/role-tag-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/role-tag-demo")
      ),
    },
  ],
  [
    "scrollbar-demo",
    {
      name: "scrollbar-demo",
      type: "registry:example",
      registryDependencies: ["scrollbar"],
      files: ["registry/bases/newt/examples/scrollbar-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/scrollbar-demo")
      ),
    },
  ],
  [
    "select-menu-demo",
    {
      name: "select-menu-demo",
      type: "registry:example",
      registryDependencies: ["select-menu"],
      files: ["registry/bases/newt/examples/select-menu-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/select-menu-demo")
      ),
    },
  ],
  [
    "server-banner-demo",
    {
      name: "server-banner-demo",
      type: "registry:example",
      registryDependencies: ["server-banner"],
      files: ["registry/bases/newt/examples/server-banner-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/server-banner-demo")
      ),
    },
  ],
  [
    "server-sidebar-demo",
    {
      name: "server-sidebar-demo",
      type: "registry:example",
      registryDependencies: ["server-sidebar"],
      files: ["registry/bases/newt/examples/server-sidebar-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/server-sidebar-demo")
      ),
    },
  ],
  [
    "skeleton-demo",
    {
      name: "skeleton-demo",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: ["registry/bases/newt/examples/skeleton-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/skeleton-demo")
      ),
    },
  ],
  [
    "slash-command-demo",
    {
      name: "slash-command-demo",
      type: "registry:example",
      registryDependencies: ["slash-command"],
      files: ["registry/bases/newt/examples/slash-command-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/slash-command-demo")
      ),
    },
  ],
  [
    "slash-command-suggestions-demo",
    {
      name: "slash-command-suggestions-demo",
      type: "registry:example",
      registryDependencies: ["slash-command-suggestions"],
      files: [
        "registry/bases/newt/examples/slash-command-suggestions-demo.tsx",
      ],
      component: React.lazy(
        () =>
          import("@/registry/bases/newt/examples/slash-command-suggestions-demo")
      ),
    },
  ],
  [
    "spoiler-demo",
    {
      name: "spoiler-demo",
      type: "registry:example",
      registryDependencies: ["spoiler"],
      files: ["registry/bases/newt/examples/spoiler-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/spoiler-demo")
      ),
    },
  ],
  [
    "stage-banner-demo",
    {
      name: "stage-banner-demo",
      type: "registry:example",
      registryDependencies: ["stage-banner"],
      files: ["registry/bases/newt/examples/stage-banner-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/stage-banner-demo")
      ),
    },
  ],
  [
    "status-indicator-demo",
    {
      name: "status-indicator-demo",
      type: "registry:example",
      registryDependencies: ["status-indicator"],
      files: ["registry/bases/newt/examples/status-indicator-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/status-indicator-demo")
      ),
    },
  ],
  [
    "tabs-demo",
    {
      name: "tabs-demo",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: ["registry/bases/newt/examples/tabs-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/tabs-demo")
      ),
    },
  ],
  [
    "timeline-demo",
    {
      name: "timeline-demo",
      type: "registry:example",
      registryDependencies: ["timeline"],
      files: ["registry/bases/newt/examples/timeline-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/timeline-demo")
      ),
    },
  ],
  [
    "toast-demo",
    {
      name: "toast-demo",
      type: "registry:example",
      registryDependencies: ["toast"],
      files: ["registry/bases/newt/examples/toast-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/toast-demo")
      ),
    },
  ],
  [
    "token-field-demo",
    {
      name: "token-field-demo",
      type: "registry:example",
      registryDependencies: ["token-field"],
      files: ["registry/bases/newt/examples/token-field-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/token-field-demo")
      ),
    },
  ],
  [
    "tooltip-demo",
    {
      name: "tooltip-demo",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: ["registry/bases/newt/examples/tooltip-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/tooltip-demo")
      ),
    },
  ],
  [
    "typing-indicator-demo",
    {
      name: "typing-indicator-demo",
      type: "registry:example",
      registryDependencies: ["typing-indicator"],
      files: ["registry/bases/newt/examples/typing-indicator-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/typing-indicator-demo")
      ),
    },
  ],
  [
    "user-profile-demo",
    {
      name: "user-profile-demo",
      type: "registry:example",
      registryDependencies: ["user-profile"],
      files: ["registry/bases/newt/examples/user-profile-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/user-profile-demo")
      ),
    },
  ],
  [
    "v2-container-demo",
    {
      name: "v2-container-demo",
      type: "registry:example",
      registryDependencies: ["v2-container"],
      files: ["registry/bases/newt/examples/v2-container-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/v2-container-demo")
      ),
    },
  ],
  [
    "voice-channel-demo",
    {
      name: "voice-channel-demo",
      type: "registry:example",
      registryDependencies: ["voice-channel"],
      files: ["registry/bases/newt/examples/voice-channel-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/bases/newt/examples/voice-channel-demo")
      ),
    },
  ],
]

export const Index = {
  default: Object.fromEntries(registryIndexEntries),
}
