// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import type { Registry } from "./schema"

export const ui: Registry = [
  {
    name: "action-row",
    type: "registry:ui",
    title: "Action Row",
    description: "The row of buttons and selects attached under a message.",
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/action-row/ActionRow.vue",
        type: "registry:ui",
      },
      {
        path: "ui/action-row/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "attachment",
    type: "registry:ui",
    title: "Attachment Card",
    description:
      "File card showing a type icon, file name, size and a download action.",
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/attachment/Attachment.vue",
        type: "registry:ui",
      },
      {
        path: "ui/attachment/AttachmentIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/attachment/AttachmentMeta.vue",
        type: "registry:ui",
      },
      {
        path: "ui/attachment/AttachmentName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/attachment/AttachmentSize.vue",
        type: "registry:ui",
      },
      {
        path: "ui/attachment/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "avatar",
    type: "registry:ui",
    title: "Avatar",
    description:
      "A circular user avatar with image support and initials fallback in three sizes.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/avatar/Avatar.vue",
        type: "registry:ui",
      },
      {
        path: "ui/avatar/AvatarImage.vue",
        type: "registry:ui",
      },
      {
        path: "ui/avatar/AvatarFallback.vue",
        type: "registry:ui",
      },
      {
        path: "ui/avatar/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "badge",
    type: "registry:ui",
    title: "Badge",
    description: "A small pill used to label status, counts or categories.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/badge/Badge.vue",
        type: "registry:ui",
      },
      {
        path: "ui/badge/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "bot-command-card",
    type: "registry:ui",
    title: "Bot Command Card",
    description:
      "A card documenting a slash command, its owning bot and its typed options.",
    registryDependencies: ["badge"],
    files: [
      {
        path: "ui/bot-command-card/BotCommandCard.vue",
        type: "registry:ui",
      },
      {
        path: "ui/bot-command-card/BotCommandCardHeader.vue",
        type: "registry:ui",
      },
      {
        path: "ui/bot-command-card/BotCommandCardName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/bot-command-card/BotCommandCardDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/bot-command-card/BotCommandCardOptions.vue",
        type: "registry:ui",
      },
      {
        path: "ui/bot-command-card/BotCommandCardOption.vue",
        type: "registry:ui",
      },
      {
        path: "ui/bot-command-card/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "button",
    type: "registry:ui",
    title: "Button",
    description:
      "Displays a Discord-styled button with brand, secondary, success, danger, link and icon variants.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/button/Button.vue",
        type: "registry:ui",
      },
      {
        path: "ui/button/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "card",
    type: "registry:ui",
    title: "Card",
    description: "A bordered, elevated panel for grouping related content.",
    files: [
      {
        path: "ui/card/Card.vue",
        type: "registry:ui",
      },
      {
        path: "ui/card/CardTitle.vue",
        type: "registry:ui",
      },
      {
        path: "ui/card/CardDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/card/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "channel-topic",
    type: "registry:ui",
    title: "Channel Topic Bar",
    description:
      "A header bar showing the channel name and a truncating topic description.",
    files: [
      {
        path: "ui/channel-topic/ChannelTopic.vue",
        type: "registry:ui",
      },
      {
        path: "ui/channel-topic/ChannelTopicIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/channel-topic/ChannelTopicName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/channel-topic/ChannelTopicDivider.vue",
        type: "registry:ui",
      },
      {
        path: "ui/channel-topic/ChannelTopicDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/channel-topic/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "chat",
    type: "registry:ui",
    title: "Chat",
    description:
      "The channel shell: a scrolling message log with the composer pinned below it.",
    registryDependencies: ["scrollbar", "message-list", "message-composer"],
    files: [
      {
        path: "ui/chat/Chat.vue",
        type: "registry:ui",
      },
      {
        path: "ui/chat/ChatBody.vue",
        type: "registry:ui",
      },
      {
        path: "ui/chat/ChatFooter.vue",
        type: "registry:ui",
      },
      {
        path: "ui/chat/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "code-block",
    type: "registry:ui",
    title: "Code Block",
    description:
      "A monospace preformatted block with optional syntax-highlight tokens.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/code-block/CodeBlock.vue",
        type: "registry:ui",
      },
      {
        path: "ui/code-block/CodeToken.vue",
        type: "registry:ui",
      },
      {
        path: "ui/code-block/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "context-menu",
    type: "registry:ui",
    title: "Context Menu",
    description:
      "A floating right-click style menu with items, keyboard shortcuts, dividers and a danger variant.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/context-menu/ContextMenu.vue",
        type: "registry:ui",
      },
      {
        path: "ui/context-menu/ContextMenuItem.vue",
        type: "registry:ui",
      },
      {
        path: "ui/context-menu/ContextMenuShortcut.vue",
        type: "registry:ui",
      },
      {
        path: "ui/context-menu/ContextMenuDivider.vue",
        type: "registry:ui",
      },
      {
        path: "ui/context-menu/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "cooldown-bar",
    type: "registry:ui",
    title: "Cooldown Bar",
    description:
      "A slim progress bar with a label and monospace countdown for command cooldowns.",
    files: [
      {
        path: "ui/cooldown-bar/CooldownBar.vue",
        type: "registry:ui",
      },
      {
        path: "ui/cooldown-bar/CooldownBarLabel.vue",
        type: "registry:ui",
      },
      {
        path: "ui/cooldown-bar/CooldownBarValue.vue",
        type: "registry:ui",
      },
      {
        path: "ui/cooldown-bar/CooldownBarTrack.vue",
        type: "registry:ui",
      },
      {
        path: "ui/cooldown-bar/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "divider",
    type: "registry:ui",
    title: "Divider",
    description:
      "A horizontal rule with an optional centered label, spacing steps and a line-less mode.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/divider/Divider.vue",
        type: "registry:ui",
      },
      {
        path: "ui/divider/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "dropdown",
    type: "registry:ui",
    title: "Dropdown Menu",
    description:
      "A floating menu panel with icon, label and description items that highlight in brand color.",
    files: [
      {
        path: "ui/dropdown/Dropdown.vue",
        type: "registry:ui",
      },
      {
        path: "ui/dropdown/DropdownItem.vue",
        type: "registry:ui",
      },
      {
        path: "ui/dropdown/DropdownIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/dropdown/DropdownContent.vue",
        type: "registry:ui",
      },
      {
        path: "ui/dropdown/DropdownLabel.vue",
        type: "registry:ui",
      },
      {
        path: "ui/dropdown/DropdownDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/dropdown/DropdownDivider.vue",
        type: "registry:ui",
      },
      {
        path: "ui/dropdown/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "embed",
    type: "registry:ui",
    title: "Embed",
    description:
      "A Discord-inspired rich message embed with an accent bar, author, title, description, fields, footer and timestamp.",
    files: [
      {
        path: "ui/embed/Embed.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedAuthor.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedAuthorIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedAuthorName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedEyebrow.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedTitle.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedFields.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedField.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedFieldName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedFieldValue.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedFooter.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedFooterIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedFooterSeparator.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/EmbedTimestamp.vue",
        type: "registry:ui",
      },
      {
        path: "ui/embed/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "empty-state",
    type: "registry:ui",
    title: "Empty State",
    description:
      "A centered placeholder with an icon, title, and hint shown when a list or view has no content.",
    files: [
      {
        path: "ui/empty-state/EmptyState.vue",
        type: "registry:ui",
      },
      {
        path: "ui/empty-state/EmptyStateIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/empty-state/EmptyStateTitle.vue",
        type: "registry:ui",
      },
      {
        path: "ui/empty-state/EmptyStateDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/empty-state/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "form-fields",
    type: "registry:ui",
    title: "Form Fields",
    description:
      "Inputs, textareas, selects, labels, helper text, switches and checkboxes styled for the newt/ui dark theme.",
    files: [
      {
        path: "ui/form-fields/Field.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/Label.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/Input.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/Textarea.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/Select.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/FieldHelp.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/Switch.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/Checkbox.vue",
        type: "registry:ui",
      },
      {
        path: "ui/form-fields/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "inline-code",
    type: "registry:ui",
    title: "Inline Code",
    description: "A monospace pill for code inside a line of message text.",
    files: [
      {
        path: "ui/inline-code/InlineCode.vue",
        type: "registry:ui",
      },
      {
        path: "ui/inline-code/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "kbd-tag",
    type: "registry:ui",
    title: "Keyboard Shortcut Tag",
    description: "A small monospace tag for displaying keyboard shortcuts.",
    files: [
      {
        path: "ui/kbd-tag/KbdTag.vue",
        type: "registry:ui",
      },
      {
        path: "ui/kbd-tag/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "member-list",
    type: "registry:ui",
    title: "Member List",
    description:
      "A server member sidebar: role sections, presence, coloured names and APP tags.",
    registryDependencies: ["avatar", "status-indicator", "role-tag"],
    files: [
      {
        path: "ui/member-list/MemberList.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListSection.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListHeading.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListItem.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListInfo.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListNameRow.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListAppTag.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/MemberListRole.vue",
        type: "registry:ui",
      },
      {
        path: "ui/member-list/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "mention",
    type: "registry:ui",
    title: "Mention Chip",
    description:
      "An inline chip for user, channel, role and app mentions, with an optional avatar.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/mention/Mention.vue",
        type: "registry:ui",
      },
      {
        path: "ui/mention/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "message-composer",
    type: "registry:ui",
    title: "Message Composer",
    description:
      "The channel input bar: attachment control, text field with combobox hooks, and send.",
    files: [
      {
        path: "ui/message-composer/MessageComposer.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-composer/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "message-group",
    type: "registry:ui",
    title: "Message Group",
    description:
      "A grouped chat message with author, timestamp, reply preview, reactions and an ephemeral state.",
    registryDependencies: [
      "avatar",
      "reaction",
      "reply-preview",
      "status-indicator",
    ],
    files: [
      {
        path: "ui/message-group/MessageGroup.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupAvatar.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupReply.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupBody.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupHeader.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupAuthor.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupBotTag.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupTime.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupContent.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupReactions.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupEphemeralNotice.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/MessageGroupEphemeralAction.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-group/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "message-list",
    type: "registry:ui",
    title: "Message List",
    description:
      "The polite live region that logs grouped messages in a channel.",
    registryDependencies: ["message-group"],
    files: [
      {
        path: "ui/message-list/MessageList.vue",
        type: "registry:ui",
      },
      {
        path: "ui/message-list/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "modal",
    type: "registry:ui",
    title: "Modal",
    description:
      "A centered dialog over a dimmed overlay that closes on Escape, overlay click or an explicit close control.",
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/modal/Modal.vue",
        type: "registry:ui",
      },
      {
        path: "ui/modal/ModalHeader.vue",
        type: "registry:ui",
      },
      {
        path: "ui/modal/ModalBody.vue",
        type: "registry:ui",
      },
      {
        path: "ui/modal/ModalFooter.vue",
        type: "registry:ui",
      },
      {
        path: "ui/modal/ModalClose.vue",
        type: "registry:ui",
      },
      {
        path: "ui/modal/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "notif-badge",
    type: "registry:ui",
    title: "Notification Badge",
    description:
      "A small count badge or unread dot for signalling new activity on avatars and channels.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "ui/notif-badge/NotifBadge.vue",
        type: "registry:ui",
      },
      {
        path: "ui/notif-badge/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "pagination",
    type: "registry:ui",
    title: "Pagination",
    description:
      "Numbered page buttons with previous/next controls, plus a divider-style load-more row.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/pagination/Pagination.vue",
        type: "registry:ui",
      },
      {
        path: "ui/pagination/PaginationButton.vue",
        type: "registry:ui",
      },
      {
        path: "ui/pagination/PaginationEllipsis.vue",
        type: "registry:ui",
      },
      {
        path: "ui/pagination/LoadMore.vue",
        type: "registry:ui",
      },
      {
        path: "ui/pagination/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "permission",
    type: "registry:ui",
    title: "Permission Row",
    description:
      "A settings row with a deny / inherit / allow tri-state toggle.",
    files: [
      {
        path: "ui/permission/Permission.vue",
        type: "registry:ui",
      },
      {
        path: "ui/permission/PermissionInfo.vue",
        type: "registry:ui",
      },
      {
        path: "ui/permission/PermissionName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/permission/PermissionDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/permission/PermissionStates.vue",
        type: "registry:ui",
      },
      {
        path: "ui/permission/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "progress",
    type: "registry:ui",
    title: "Progress Bar",
    description:
      "A gradient progress bar for boosts, uploads and other long-running tasks.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/progress/Progress.vue",
        type: "registry:ui",
      },
      {
        path: "ui/progress/ProgressLabel.vue",
        type: "registry:ui",
      },
      {
        path: "ui/progress/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "reaction",
    type: "registry:ui",
    title: "Reaction Pill",
    description:
      "A toggleable emoji reaction pill, plus the group that rows them under a message.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/reaction/Reaction.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reaction/ReactionGroup.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reaction/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "reply-preview",
    type: "registry:ui",
    title: "Reply Preview",
    description:
      'A compact "replying to" bar showing the author, a truncated excerpt, or the slash command that was used.',
    files: [
      {
        path: "ui/reply-preview/ReplyPreview.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reply-preview/ReplyPreviewAvatar.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reply-preview/ReplyPreviewAuthor.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reply-preview/ReplyPreviewText.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reply-preview/ReplyPreviewAction.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reply-preview/ReplyPreviewCommand.vue",
        type: "registry:ui",
      },
      {
        path: "ui/reply-preview/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "role-tag",
    type: "registry:ui",
    title: "Role Tag",
    description:
      "A compact bordered tag with a coloured dot for displaying a member's role.",
    files: [
      {
        path: "ui/role-tag/RoleTag.vue",
        type: "registry:ui",
      },
      {
        path: "ui/role-tag/RoleTagDot.vue",
        type: "registry:ui",
      },
      {
        path: "ui/role-tag/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "scrollbar",
    type: "registry:ui",
    title: "Scrollbar Utility",
    description:
      "Discord-styled scrollbars for any scrollable container, with an optional keyboard-focusable viewport.",
    files: [
      {
        path: "ui/scrollbar/ScrollArea.vue",
        type: "registry:ui",
      },
      {
        path: "ui/scrollbar/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "select-menu",
    type: "registry:ui",
    title: "Select Menu",
    description:
      "A Discord-inspired string select: combobox trigger, keyboard-driven listbox and a portalled panel.",
    files: [
      {
        path: "ui/select-menu/SelectMenu.vue",
        type: "registry:ui",
      },
      {
        path: "ui/select-menu/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "server-banner",
    type: "registry:ui",
    title: "Server Banner",
    description:
      "Invite-style card with a server icon, name, live member counts and a join button.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["button"],
    files: [
      {
        path: "ui/server-banner/ServerBanner.vue",
        type: "registry:ui",
      },
      {
        path: "ui/server-banner/ServerBannerIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/server-banner/ServerBannerInfo.vue",
        type: "registry:ui",
      },
      {
        path: "ui/server-banner/ServerBannerName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/server-banner/ServerBannerMeta.vue",
        type: "registry:ui",
      },
      {
        path: "ui/server-banner/ServerBannerMetaItem.vue",
        type: "registry:ui",
      },
      {
        path: "ui/server-banner/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    title: "Skeleton Loader",
    description: "A shimmering placeholder shown while content is loading.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/skeleton/Skeleton.vue",
        type: "registry:ui",
      },
      {
        path: "ui/skeleton/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "slash-command",
    type: "registry:ui",
    title: "Slash Command",
    description:
      "An inline /command with its subcommand path and typed options, including the focused one.",
    files: [
      {
        path: "ui/slash-command/SlashCommand.vue",
        type: "registry:ui",
      },
      {
        path: "ui/slash-command/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "spoiler",
    type: "registry:ui",
    title: "Spoiler",
    description:
      "Inline text hidden behind a dark block until the reader clicks to reveal it.",
    files: [
      {
        path: "ui/spoiler/Spoiler.vue",
        type: "registry:ui",
      },
      {
        path: "ui/spoiler/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "stage-banner",
    type: "registry:ui",
    title: "Stage Banner",
    description:
      "A full-width announcement strip with a status dot, optional action button and dismiss control.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/stage-banner/StageBanner.vue",
        type: "registry:ui",
      },
      {
        path: "ui/stage-banner/StageBannerDot.vue",
        type: "registry:ui",
      },
      {
        path: "ui/stage-banner/StageBannerAction.vue",
        type: "registry:ui",
      },
      {
        path: "ui/stage-banner/StageBannerClose.vue",
        type: "registry:ui",
      },
      {
        path: "ui/stage-banner/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "status-indicator",
    type: "registry:ui",
    title: "Status Indicator",
    description:
      "A presence dot anchored to an avatar, with online, idle, do-not-disturb, offline and streaming states.",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["avatar"],
    files: [
      {
        path: "ui/status-indicator/StatusIndicator.vue",
        type: "registry:ui",
      },
      {
        path: "ui/status-indicator/StatusDot.vue",
        type: "registry:ui",
      },
      {
        path: "ui/status-indicator/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "tabs",
    type: "registry:ui",
    title: "Tabs",
    description: "A pill-style tab list that switches the active tab on click.",
    files: [
      {
        path: "ui/tabs/Tabs.vue",
        type: "registry:ui",
      },
      {
        path: "ui/tabs/TabsTrigger.vue",
        type: "registry:ui",
      },
      {
        path: "ui/tabs/TabsContent.vue",
        type: "registry:ui",
      },
      {
        path: "ui/tabs/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "timeline",
    type: "registry:ui",
    title: "Event Timeline",
    description:
      "A vertical event log with connected status dots, titles and metadata.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/timeline/Timeline.vue",
        type: "registry:ui",
      },
      {
        path: "ui/timeline/TimelineItem.vue",
        type: "registry:ui",
      },
      {
        path: "ui/timeline/TimelineDot.vue",
        type: "registry:ui",
      },
      {
        path: "ui/timeline/TimelineContent.vue",
        type: "registry:ui",
      },
      {
        path: "ui/timeline/TimelineTitle.vue",
        type: "registry:ui",
      },
      {
        path: "ui/timeline/TimelineMeta.vue",
        type: "registry:ui",
      },
      {
        path: "ui/timeline/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "toast",
    type: "registry:ui",
    title: "Toast",
    description:
      "A transient notification with a status icon that auto-dismisses after a timeout or when closed.",
    dependencies: ["class-variance-authority"],
    files: [
      {
        path: "ui/toast/Toast.vue",
        type: "registry:ui",
      },
      {
        path: "ui/toast/ToastIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/toast/ToastContent.vue",
        type: "registry:ui",
      },
      {
        path: "ui/toast/ToastTitle.vue",
        type: "registry:ui",
      },
      {
        path: "ui/toast/ToastDescription.vue",
        type: "registry:ui",
      },
      {
        path: "ui/toast/ToastClose.vue",
        type: "registry:ui",
      },
      {
        path: "ui/toast/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "token-field",
    type: "registry:ui",
    title: "Token Field",
    description:
      "A read-only, masked monospace input with reveal and copy-to-clipboard actions for secrets such as bot tokens.",
    registryDependencies: ["form-fields", "button"],
    files: [
      {
        path: "ui/token-field/TokenField.vue",
        type: "registry:ui",
      },
      {
        path: "ui/token-field/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "tooltip",
    type: "registry:ui",
    title: "Tooltip",
    description:
      "A small floating label that appears above an element on hover or focus.",
    files: [
      {
        path: "ui/tooltip/Tooltip.vue",
        type: "registry:ui",
      },
      {
        path: "ui/tooltip/TooltipTrigger.vue",
        type: "registry:ui",
      },
      {
        path: "ui/tooltip/TooltipContent.vue",
        type: "registry:ui",
      },
      {
        path: "ui/tooltip/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "typing-indicator",
    type: "registry:ui",
    title: "Typing Indicator",
    description:
      "Three bouncing dots with a label that signals someone is typing.",
    files: [
      {
        path: "ui/typing-indicator/TypingIndicator.vue",
        type: "registry:ui",
      },
      {
        path: "ui/typing-indicator/TypingIndicatorDots.vue",
        type: "registry:ui",
      },
      {
        path: "ui/typing-indicator/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "user-profile",
    type: "registry:ui",
    title: "User Profile Popout",
    description:
      "Floating profile card with a banner, overlapping avatar, bio section and role tags.",
    registryDependencies: ["avatar", "status-indicator", "role-tag", "button"],
    files: [
      {
        path: "ui/user-profile/UserProfile.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileBanner.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileHead.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileActions.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileAvatar.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileName.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileHandle.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileDivider.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileBody.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileSectionLabel.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileBio.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/UserProfileRoles.vue",
        type: "registry:ui",
      },
      {
        path: "ui/user-profile/index.ts",
        type: "registry:ui",
      },
    ],
  },
  {
    name: "voice-channel",
    type: "registry:ui",
    title: "Voice Channel Row",
    description:
      "A sidebar voice channel row with a collapsible header and the list of connected members.",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "ui/voice-channel/VoiceChannel.vue",
        type: "registry:ui",
      },
      {
        path: "ui/voice-channel/VoiceChannelHeader.vue",
        type: "registry:ui",
      },
      {
        path: "ui/voice-channel/VoiceChannelIcon.vue",
        type: "registry:ui",
      },
      {
        path: "ui/voice-channel/VoiceChannelMembers.vue",
        type: "registry:ui",
      },
      {
        path: "ui/voice-channel/VoiceChannelMember.vue",
        type: "registry:ui",
      },
      {
        path: "ui/voice-channel/VoiceChannelMemberIcons.vue",
        type: "registry:ui",
      },
      {
        path: "ui/voice-channel/index.ts",
        type: "registry:ui",
      },
    ],
  },
]
