// This file is autogenerated by scripts/gen-registry.mjs — do not edit.
import type { Registry } from "./schema"

export const examples: Registry = [
  {
    name: "AttachmentDemo",
    type: "registry:example",
    registryDependencies: ["attachment"],
    files: [
      {
        path: "example/AttachmentDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "AvatarDemo",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [
      {
        path: "example/AvatarDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "BadgeDemo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [
      {
        path: "example/BadgeDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "BotCommandCardDemo",
    type: "registry:example",
    registryDependencies: ["bot-command-card"],
    files: [
      {
        path: "example/BotCommandCardDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ButtonDemo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "example/ButtonDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "CardDemo",
    type: "registry:example",
    registryDependencies: ["card"],
    files: [
      {
        path: "example/CardDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ChannelTopicDemo",
    type: "registry:example",
    registryDependencies: ["channel-topic"],
    files: [
      {
        path: "example/ChannelTopicDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "CodeBlockDemo",
    type: "registry:example",
    registryDependencies: ["code-block"],
    files: [
      {
        path: "example/CodeBlockDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ContextMenuDemo",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    files: [
      {
        path: "example/ContextMenuDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "CooldownBarDemo",
    type: "registry:example",
    registryDependencies: ["cooldown-bar"],
    files: [
      {
        path: "example/CooldownBarDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "DividerDemo",
    type: "registry:example",
    registryDependencies: ["divider"],
    files: [
      {
        path: "example/DividerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "DropdownDemo",
    type: "registry:example",
    registryDependencies: ["dropdown"],
    files: [
      {
        path: "example/DropdownDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "EmbedDemo",
    type: "registry:example",
    registryDependencies: ["embed"],
    files: [
      {
        path: "example/EmbedDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "EmptyStateDemo",
    type: "registry:example",
    registryDependencies: ["empty-state"],
    files: [
      {
        path: "example/EmptyStateDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "FormFieldsDemo",
    type: "registry:example",
    registryDependencies: ["form-fields"],
    files: [
      {
        path: "example/FormFieldsDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "KbdTagDemo",
    type: "registry:example",
    registryDependencies: ["kbd-tag"],
    files: [
      {
        path: "example/KbdTagDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MemberListDemo",
    type: "registry:example",
    registryDependencies: ["member-list"],
    files: [
      {
        path: "example/MemberListDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MentionDemo",
    type: "registry:example",
    registryDependencies: ["mention"],
    files: [
      {
        path: "example/MentionDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "MessageGroupDemo",
    type: "registry:example",
    registryDependencies: ["message-group"],
    files: [
      {
        path: "example/MessageGroupDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ModalDemo",
    type: "registry:example",
    registryDependencies: ["modal"],
    files: [
      {
        path: "example/ModalDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "NotifBadgeDemo",
    type: "registry:example",
    registryDependencies: ["notif-badge"],
    files: [
      {
        path: "example/NotifBadgeDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "PaginationDemo",
    type: "registry:example",
    registryDependencies: ["pagination"],
    files: [
      {
        path: "example/PaginationDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "PermissionDemo",
    type: "registry:example",
    registryDependencies: ["permission"],
    files: [
      {
        path: "example/PermissionDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ProgressDemo",
    type: "registry:example",
    registryDependencies: ["progress"],
    files: [
      {
        path: "example/ProgressDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ReactionDemo",
    type: "registry:example",
    registryDependencies: ["reaction"],
    files: [
      {
        path: "example/ReactionDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ReplyPreviewDemo",
    type: "registry:example",
    registryDependencies: ["reply-preview"],
    files: [
      {
        path: "example/ReplyPreviewDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "RoleTagDemo",
    type: "registry:example",
    registryDependencies: ["role-tag"],
    files: [
      {
        path: "example/RoleTagDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ScrollbarDemo",
    type: "registry:example",
    registryDependencies: ["scrollbar"],
    files: [
      {
        path: "example/ScrollbarDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SelectMenuDemo",
    type: "registry:example",
    registryDependencies: ["select-menu"],
    files: [
      {
        path: "example/SelectMenuDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ServerBannerDemo",
    type: "registry:example",
    registryDependencies: ["server-banner"],
    files: [
      {
        path: "example/ServerBannerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SkeletonDemo",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: [
      {
        path: "example/SkeletonDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SlashCommandDemo",
    type: "registry:example",
    registryDependencies: ["slash-command"],
    files: [
      {
        path: "example/SlashCommandDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "SpoilerDemo",
    type: "registry:example",
    registryDependencies: ["spoiler"],
    files: [
      {
        path: "example/SpoilerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "StageBannerDemo",
    type: "registry:example",
    registryDependencies: ["stage-banner"],
    files: [
      {
        path: "example/StageBannerDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "StatusIndicatorDemo",
    type: "registry:example",
    registryDependencies: ["status-indicator"],
    files: [
      {
        path: "example/StatusIndicatorDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TabsDemo",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [
      {
        path: "example/TabsDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TimelineDemo",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: [
      {
        path: "example/TimelineDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "ToastDemo",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: [
      {
        path: "example/ToastDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TokenFieldDemo",
    type: "registry:example",
    registryDependencies: ["token-field"],
    files: [
      {
        path: "example/TokenFieldDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TooltipDemo",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    files: [
      {
        path: "example/TooltipDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "TypingIndicatorDemo",
    type: "registry:example",
    registryDependencies: ["typing-indicator"],
    files: [
      {
        path: "example/TypingIndicatorDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "UserProfileDemo",
    type: "registry:example",
    registryDependencies: ["user-profile"],
    files: [
      {
        path: "example/UserProfileDemo.vue",
        type: "registry:example",
      },
    ],
  },
  {
    name: "VoiceChannelDemo",
    type: "registry:example",
    registryDependencies: ["voice-channel"],
    files: [
      {
        path: "example/VoiceChannelDemo.vue",
        type: "registry:example",
      },
    ],
  },
]
