import { z } from "zod"

import { FRAMEWORK_IDS, INSTALL_TARGETS } from "./install-targets"

/*
 * The newt/create codec, a second time.
 *
 * `packages/cli/src/utils/preset.ts` is the other copy. The documentation site
 * may not import CLI source — they are separate published artefacts with
 * separate dependency trees — so the two are kept honest by a golden fixture
 * committed to both, asserted byte-identical, and generated by the CLI itself.
 * Change one and the other's test fails on the next run, which is the point.
 */
export const PRESET_VERSION = 1
export const PRESET_PREFIX = `nt${PRESET_VERSION}.`

export const PRESET_RADII = ["sm", "md", "lg"] as const
export const PRESET_FONTS = ["inter", "system", "mono-first"] as const
export const PRESET_MODES = ["dark", "light"] as const
export const PRESET_DIRECTIONS = ["ltr", "rtl"] as const

export type PresetRadius = (typeof PRESET_RADII)[number]
export type PresetFont = (typeof PRESET_FONTS)[number]
export type PresetMode = (typeof PRESET_MODES)[number]
export type PresetDirection = (typeof PRESET_DIRECTIONS)[number]

/** The four `init --template` can create from nothing. */
export const PRESET_TEMPLATES = [
  "next",
  "vite-react",
  "vite-vue",
  "nuxt",
] as const
export type PresetTemplate = (typeof PRESET_TEMPLATES)[number]

export class PresetError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "PresetError"
  }
}

/*
 * The same schema the CLI declares, over the same one-letter keys — they are
 * spent in a URL and on a command line, and this is the only place that knows
 * what they stand for.
 */
export const presetSchema = z.object({
  v: z.literal(PRESET_VERSION),
  t: z.enum(FRAMEWORK_IDS),
  b: z.string().regex(/^#[0-9a-f]{6}$/i, "expected a #rrggbb colour"),
  r: z.enum(PRESET_RADII),
  f: z.enum(PRESET_FONTS),
  m: z.enum(PRESET_MODES),
  d: z.enum(PRESET_DIRECTIONS),
})

export type Preset = z.infer<typeof presetSchema>

export const DEFAULT_PRESET: Preset = {
  v: PRESET_VERSION,
  t: "next",
  b: "#5865f2",
  r: "md",
  f: "inter",
  m: "dark",
  d: "ltr",
}

function toBase64Url(json: string): string {
  return btoa(json).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "")
}

function fromBase64Url(code: string): string {
  return atob(code.replaceAll("-", "+").replaceAll("_", "/"))
}

/** Key order is fixed, so the same choices always produce the same code. */
export function encodePreset(preset: Preset): string {
  const parsed = presetSchema.parse(preset)
  const ordered = {
    v: parsed.v,
    t: parsed.t,
    b: parsed.b.toLowerCase(),
    r: parsed.r,
    f: parsed.f,
    m: parsed.m,
    d: parsed.d,
  }
  return `${PRESET_PREFIX}${toBase64Url(JSON.stringify(ordered))}`
}

export function decodePreset(code: string): Preset {
  const trimmed = code.trim()
  if (!trimmed.startsWith(PRESET_PREFIX)) {
    throw new PresetError(
      `"${trimmed}" is not a preset code — they start with "${PRESET_PREFIX}".`
    )
  }

  let json: string
  try {
    json = fromBase64Url(trimmed.slice(PRESET_PREFIX.length))
  } catch {
    throw new PresetError("That preset code is not valid base64url.")
  }

  /*
   * Parsed at the boundary rather than inspected: a payload that is merely the
   * right shape is not the same as one whose values the builder can render.
   */
  let result: ReturnType<typeof presetSchema.safeParse>
  try {
    result = presetSchema.safeParse(JSON.parse(json))
  } catch {
    throw new PresetError("That preset code does not carry valid JSON.")
  }
  if (!result.success) {
    const [issue] = result.error.issues
    const where = issue?.path.join(".")
    throw new PresetError(
      `That preset code is not valid: ${issue?.message ?? "unknown field"}${
        where ? ` (${where})` : ""
      }.`
    )
  }
  return { ...result.data, b: result.data.b.toLowerCase() }
}

export function templateFor(preset: Preset): PresetTemplate | undefined {
  return PRESET_TEMPLATES.find((template) => template === preset.t)
}

/**
 * The hover and active steps are the base darkened. A picker that offers one
 * colour still has to produce the three the components read.
 */
function darken(hex: string, amount: number): string {
  const value = Number.parseInt(hex.slice(1), 16)
  const channels = [value >> 16, (value >> 8) & 0xff, value & 0xff]
  return `#${channels
    .map((channel) =>
      Math.round(channel * (1 - amount))
        .toString(16)
        .padStart(2, "0")
    )
    .join("")}`
}

const RADIUS_SCALES = {
  sm: { sm: "2px", md: "4px", lg: "6px" },
  md: { sm: "4px", md: "8px", lg: "12px" },
  lg: { sm: "6px", md: "12px", lg: "18px" },
} as const satisfies Record<PresetRadius, Record<"sm" | "md" | "lg", string>>

const FONT_STACKS = {
  inter: {
    sans: '"Inter", "gg sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    display: '"Inter", sans-serif',
  },
  system: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    display:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  "mono-first": {
    sans: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
    display: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
  },
} as const satisfies Record<PresetFont, { sans: string; display: string }>

export const PRESET_MARKER = "/* newt/ui preset"
export const PRESET_END_MARKER = "/* end newt/ui preset */"

/** Byte for byte what `newtui preset css` prints, which the fixture pins. */
export function presetToCss(preset: Preset): string {
  const code = encodePreset(preset)
  const radius = RADIUS_SCALES[preset.r]
  const font = FONT_STACKS[preset.f]

  const lines = [
    `${PRESET_MARKER} ${code} — newt/create */`,
    ":root {",
    `  --newt-brand: ${preset.b};`,
    `  --newt-brand-hover: ${darken(preset.b, 0.15)};`,
    `  --newt-brand-active: ${darken(preset.b, 0.3)};`,
    "",
    `  --newt-radius-sm: ${radius.sm};`,
    `  --newt-radius-md: ${radius.md};`,
    `  --newt-radius-lg: ${radius.lg};`,
    "",
    `  --newt-font-sans: ${font.sans};`,
    `  --newt-font-display: ${font.display};`,
    "}",
  ]

  if (preset.m === "light") {
    lines.push(
      "",
      '/* Light is the default surface set: put data-newt-theme="light" on <html>. */',
      ":root {",
      "  color-scheme: light;",
      "}"
    )
  }

  if (preset.d === "rtl") {
    lines.push(
      "",
      '/* Right to left by default: dir="rtl" belongs on <html> as well. */',
      ":root {",
      "  --newt-dir: -1;",
      "}"
    )
  }

  lines.push("", PRESET_END_MARKER)
  return `${lines.join("\n")}\n`
}

/** One custom property the live preview writes, and the CSS block declares. */
export interface PresetVariable {
  readonly property: string
  readonly value: string
}

export function presetVariables(preset: Preset): readonly PresetVariable[] {
  const radius = RADIUS_SCALES[preset.r]
  const font = FONT_STACKS[preset.f]
  return [
    { property: "--newt-brand", value: preset.b },
    { property: "--newt-brand-hover", value: darken(preset.b, 0.15) },
    { property: "--newt-brand-active", value: darken(preset.b, 0.3) },
    { property: "--newt-radius-sm", value: radius.sm },
    { property: "--newt-radius-md", value: radius.md },
    { property: "--newt-radius-lg", value: radius.lg },
    { property: "--newt-font-sans", value: font.sans },
    { property: "--newt-font-display", value: font.display },
  ]
}

export type PackageManager = "pnpm" | "npm" | "yarn" | "bun"

const RUNNERS = {
  pnpm: "pnpm dlx",
  npm: "npx",
  yarn: "yarn dlx",
  bun: "bunx",
} as const satisfies Record<PackageManager, string>

/**
 * What the builder prints. A target with a template gets one command; the rest
 * get their own creator first, because pretending `--template laravel` exists
 * would only fail in the reader's terminal.
 */
export function presetCommands(
  preset: Preset,
  packageManager: PackageManager
): readonly string[] {
  const runner = RUNNERS[packageManager]
  const template = templateFor(preset)
  const target = INSTALL_TARGETS.find((entry) => entry.id === preset.t)
  const code = encodePreset(preset)

  if (template !== undefined) {
    return [
      `${runner} newtui@latest init --template ${template} --preset ${code}`,
    ]
  }
  const commands: string[] = []
  if (target?.scaffold !== undefined) {
    commands.push(`${runner} ${target.scaffold}`)
  }
  commands.push(`${runner} newtui@latest init --preset ${code}`)
  return commands
}

/** For a project that has already run `init`. */
export function applyCommand(
  preset: Preset,
  packageManager: PackageManager
): string {
  return `${RUNNERS[packageManager]} newtui@latest apply --preset ${encodePreset(preset)}`
}
