name: Semantic Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  semantic-pr:
    permissions:
      contents: read
      pull-requests: read # analyze pull requests
      statuses: write # publish validation status
    runs-on: ubuntu-latest
    name: 🏷️ Validate PR title
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        with:
          scopes: |
            www
            vue
            newt-ui
            cli
            module
            registry
            ci
            deps
            docs
            release
            templates
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

            Examples:
              ✅ feat(www): add voice-channel docs page
              ✅ docs: update README
              ❌ feat(www): Add voice-channel docs page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
